/** كلمة الجماعة + كلمة قريبة للامبوستر (نفس التصنيف، ليست نفس الكلمة) */
export type ImposterPair = { word: string; impostorWord: string };

export const IMPOSTER_PAIRS: Record<string, ImposterPair[]> = {
  animals: [
    { word: "فراخ", impostorWord: "بط" },
    { word: "خروف", impostorWord: "ماعز" },
    { word: "بقرة", impostorWord: "جاموس" },
    { word: "قطة", impostorWord: "كلب" },
    { word: "أسد", impostorWord: "نمر" },
    { word: "فيل", impostorWord: "وحيد القرن" },
    { word: "حصان", impostorWord: "حمار" },
    { word: "أرنب", impostorWord: "هامستر" },
    { word: "دجاجة", impostorWord: "بطة" },
    { word: "سمكة", impostorWord: "جمبري" },
    { word: "نسر", impostorWord: "صقر" },
    { word: "ببغاء", impostorWord: "عصفور" },
    { word: "ثعبان", impostorWord: "سحلية" },
    { word: "قرد", impostorWord: "غوريلا" },
    { word: "دب", impostorWord: "باندا" },
    { word: "ذئب", impostorWord: "ثعلب" },
    { word: "زرافة", impostorWord: "جمل" },
    { word: "باندا", impostorWord: "كوالا" },
    { word: "دولفين", impostorWord: "حوت" },
    { word: "سلحفاة", impostorWord: "سلطعون" },
    { word: "نحلة", impostorWord: "دبور" },
    { word: "فراشة", impostorWord: "عثة" },
    { word: "عنكبوت", impostorWord: "عقرب" },
    { word: "جمل", impostorWord: "حمار وحشي" },
    { word: "كنغر", impostorWord: "ولد النعام" },
    { word: "فهد", impostorWord: "نمر" },
    { word: "غزال", impostorWord: "ظبي" },
    { word: "بطريق", impostorWord: "بجعة" },
    { word: "حمامة", impostorWord: "غراب" },
    { word: "ثور", impostorWord: "ثور البقر" },
    { word: "خنزير", impostorWord: "خنزير بري" },
    { word: "ديك", impostorWord: "ديك رومي" },
    { word: "بجعة", impostorWord: "بطة" },
    { word: "فأر", impostorWord: "جرذ" },
    { word: "خفاش", impostorWord: "بومة" },
    { word: "حمار", impostorWord: "بغل" },
    { word: "نعجة", impostorWord: "ماعز" },
    { word: "عجل", impostorWord: "عجل البقر" },
    { word: "قنديل", impostorWord: "سمك القرش" },
    { word: "حوت", impostorWord: "دلفين" },
    { word: "تمساح", impostorWord: "تمساح النيل" },
    { word: "ضفدع", impostorWord: "علجوم" },
    { word: "ببغاء", impostorWord: "بومة" },
    { word: "قط", impostorWord: "قط بري" },
    { word: "كلب", impostorWord: "ذئب" },
    { word: "حمار وحشي", impostorWord: "حصان" },
    { word: "غوريلا", impostorWord: "شمبانزي" },
    { word: "فهد", impostorWord: "نمر" },
    { word: "باندا", impostorWord: "دب" },
    { word: "زرافة", impostorWord: "وحيد القرن" },
    { word: "دجاج", impostorWord: "بط" },
  ],
  countries: [
    { word: "مصر", impostorWord: "السودان" },
    { word: "السعودية", impostorWord: "الإمارات" },
    { word: "الإمارات", impostorWord: "قطر" },
    { word: "قطر", impostorWord: "البحرين" },
    { word: "الكويت", impostorWord: "البحرين" },
    { word: "الأردن", impostorWord: "فلسطين" },
    { word: "لبنان", impostorWord: "سوريا" },
    { word: "المغرب", impostorWord: "تونس" },
    { word: "تونس", impostorWord: "الجزائر" },
    { word: "الجزائر", impostorWord: "المغرب" },
    { word: "تركيا", impostorWord: "اليونان" },
    { word: "فرنسا", impostorWord: "إيطاليا" },
    { word: "إيطاليا", impostorWord: "إسبانيا" },
    { word: "إسبانيا", impostorWord: "البرتغال" },
    { word: "ألمانيا", impostorWord: "النمسا" },
    { word: "بريطانيا", impostorWord: "أيرلندا" },
    { word: "أمريكا", impostorWord: "كندا" },
    { word: "كندا", impostorWord: "أمريكا" },
    { word: "البرازيل", impostorWord: "الأرجنتين" },
    { word: "الأرجنتين", impostorWord: "تشيلي" },
    { word: "اليابان", impostorWord: "كوريا" },
    { word: "الصين", impostorWord: "اليابان" },
    { word: "الهند", impostorWord: "باكستان" },
    { word: "روسيا", impostorWord: "أوكرانيا" },
    { word: "أستراليا", impostorWord: "نيوزيلندا" },
    { word: "إندونيسيا", impostorWord: "ماليزيا" },
    { word: "تايلاند", impostorWord: "فيتنام" },
    { word: "إيران", impostorWord: "العراق" },
    { word: "العراق", impostorWord: "سوريا" },
    { word: "عمان", impostorWord: "اليمن" },
    { word: "اليمن", impostorWord: "عمان" },
    { word: "ليبيا", impostorWord: "تونس" },
    { word: "السودان", impostorWord: "مصر" },
    { word: "فلسطين", impostorWord: "الأردن" },
    { word: "هولندا", impostorWord: "بلجيكا" },
    { word: "سويسرا", impostorWord: "النمسا" },
    { word: "السويد", impostorWord: "النرويج" },
    { word: "النرويج", impostorWord: "الدنمارك" },
    { word: "بولندا", impostorWord: "التشيك" },
    { word: "المكسيك", impostorWord: "كولومبيا" },
    { word: "كوبا", impostorWord: "جمهورية الدومينيكان" },
    { word: "نيجيريا", impostorWord: "غانا" },
    { word: "كينيا", impostorWord: "إثيوبيا" },
    { word: "جنوب أفريقيا", impostorWord: "نيجيريا" },
    { word: "سنغافورة", impostorWord: "ماليزيا" },
    { word: "الفلبين", impostorWord: "إندونيسيا" },
    { word: "باكستان", impostorWord: "أفغانستان" },
    { word: "نيبال", impostorWord: "الهند" },
    { word: "فنزويلا", impostorWord: "البرازيل" },
    { word: "بيرو", impostorWord: "الإكوادور" },
    { word: "اليونان", impostorWord: "قبرص" },
  ],
  football: [
    { word: "ميسي", impostorWord: "مارادونا" },
    { word: "رونالدو", impostorWord: "بيل" },
    { word: "صلاح", impostorWord: "ماني" },
    { word: "محمد صلاح", impostorWord: "محمد النني" },
    { word: "مبابي", impostorWord: "بنزيما" },
    { word: "هالاند", impostorWord: "لوكاكو" },
    { word: "نيمار", impostorWord: "كاكا" },
    { word: "مودريتش", impostorWord: "توني كروس" },
    { word: "ديبروين", impostorWord: "برونو فيرنانديز" },
    { word: "بنزيما", impostorWord: "كريم بنزيما" },
    { word: "ليفاندوفسكي", impostorWord: "هالاند" },
    { word: "كريستيانو", impostorWord: "رونالدو البرازيلي" },
    { word: "إنييستا", impostorWord: "تشافي" },
    { word: "تشافي", impostorWord: "إنييستا" },
    { word: "زيدان", impostorWord: "رونالدينيو" },
    { word: "رونالدينيو", impostorWord: "كاكا" },
    { word: "بوفون", impostorWord: "كاسياس" },
    { word: "كاسياس", impostorWord: "نوير" },
    { word: "نوير", impostorWord: "أليسون" },
    { word: "أبيدي بيليه", impostorWord: "رونالدو" },
    { word: "جيرارد", impostorWord: "لامبارد" },
    { word: "لامبارد", impostorWord: "سكولز" },
    { word: "روoney", impostorWord: "فان بيرسي" },
    { word: "أجويرو", impostorWord: "توريس" },
    { word: "سواريز", impostorWord: "كافاني" },
    { word: "كافاني", impostorWord: "سواريز" },
    { word: "محمد أبو تريكة", impostorWord: "عماد متعب" },
    { word: "عماد متعب", impostorWord: "أحمد حسن" },
    { word: "أحمد حسن", impostorWord: "حسام غالي" },
    { word: "حسام البدري", impostorWord: "حسام حسن" },
    { word: "كريم بنزيما", impostorWord: "كريم عبدالعزيز" },
    { word: "جون تيري", impostorWord: "ريو فرديناند" },
    { word: "ميلان باريشيتش", impostorWord: "مودريتش" },
    { word: "ساديو مانé", impostorWord: "صلاح" },
    { word: "فينيسيوس", impostorWord: "رودريغو" },
    { word: "بيدري", impostorWord: "غافي" },
    { word: "غافي", impostorWord: "بيدري" },
    { word: "سيرجيو راموس", impostorWord: "بيبي" },
    { word: "فيرجيل فان دايك", impostorWord: "دياز" },
    { word: "كوليبالي", impostorWord: "فيرجيل" },
    { word: "محرز", impostorWord: "غريزمان" },
    { word: "غريزمان", impostorWord: "جريزمان" },
    { word: "كانتي", impostorWord: "كوفاسيتش" },
    { word: "بوكبا", impostorWord: "ماتيتش" },
    { word: "إبراهيموفيتش", impostorWord: "كافاني" },
    { word: "هاري كين", impostorWord: "سون" },
    { word: "سون", impostorWord: "كين" },
    { word: "أوباميانج", impostorWord: "لاكازيت" },
    { word: "جاك", impostorWord: "جيرو" },
    { word: "جيرو", impostorWord: "جاك" },
    { word: "دروجبا", impostorWord: "إيتو" },
    { word: "إيتو", impostorWord: "دروجبا" },
  ],
  clothing: [
    { word: "قميص", impostorWord: "بلوزة" },
    { word: "بنطلون", impostorWord: "جينز" },
    { word: "فستان", impostorWord: "عباية" },
    { word: "جاكيت", impostorWord: "كوت" },
    { word: "حذاء", impostorWord: "صندل" },
    { word: "جوارب", impostorWord: "شراب" },
    { word: "طرحه", impostorWord: "شال" },
    { word: "حجاب", impostorWord: "طرحة" },
    { word: "نظارة", impostorWord: "عدسة" },
    { word: "ساعة", impostorWord: "سوار" },
    { word: "قبعة", impostorWord: "طاقية" },
    { word: "كوفية", impostorWord: "شماغ" },
    { word: "بدلة", impostorWord: "كوت" },
    { word: "ربطة عنق", impostorWord: "فيونكة" },
    { word: "حزام", impostorWord: "حمالة" },
    { word: "بلوزة", impostorWord: "قميص" },
    { word: "كلسون", impostorWord: "بوكسر" },
    { word: "مايوه", impostorWord: "شورت سباحة" },
    { word: "بيجاما", impostorWord: "روب" },
    { word: "روب", impostorWord: "بيجاما" },
    { word: "معطف", impostorWord: "جاكيت" },
    { word: "كاب", impostorWord: "معطف" },
    { word: "جينز", impostorWord: "بنطلون" },
    { word: "كوت", impostorWord: "جاكيت" },
    { word: "صندل", impostorWord: "شبشب" },
    { word: "كندرة", impostorWord: "صندل" },
    { word: "جزمة", impostorWord: "حذاء" },
    { word: "شنطة", impostorWord: "حقيبة" },
    { word: "حقيبة ظهر", impostorWord: "شنطة" },
    { word: "محفظة", impostorWord: "شنطة يد" },
    { word: "قفاز", impostorWord: "كشاف" },
    { word: "وشاح", impostorWord: "طرحة" },
    { word: "طوق", impostorWord: "سلسلة" },
    { word: "خاتم", impostorWord: "سوار" },
    { word: "حلق", impostorWord: "خاتم" },
    { word: "نظارة شمس", impostorWord: "نظارة طبية" },
    { word: "كاب", impostorWord: "قبعة" },
    { word: "طاقية", impostorWord: "قبعة" },
    { word: "فيونكة", impostorWord: "ربطة عنق" },
    { word: "كلسون طويل", impostorWord: "جوارب" },
    { word: "شراب", impostorWord: "جوارب" },
    { word: "بلوفر", impostorWord: "سويتر" },
    { word: "سويتر", impostorWord: "بلوفر" },
    { word: "هودي", impostorWord: "سويتر" },
    { word: "كارديجان", impostorWord: "بلوفر" },
    { word: "تنورة", impostorWord: "فستان" },
    { word: "شورت", impostorWord: "بنطلون" },
    { word: "شماغ", impostorWord: "كوفية" },
    { word: "غترة", impostorWord: "طاقية" },
    { word: "عباية", impostorWord: "فستان" },
    { word: "جلباب", impostorWord: "جلابية" },
    { word: "جلابية", impostorWord: "جلباب" },
  ],
  egyptian_food: [
    { word: "كشري", impostorWord: "مكرونة بشاميل" },
    { word: "فول", impostorWord: "طعمية" },
    { word: "طعمية", impostorWord: "فلافل" },
    { word: "ملوخية", impostorWord: "بامية" },
    { word: "محشي", impostorWord: "ملفوف" },
    { word: "كبدة", impostorWord: "سجق" },
    { word: "شاورما", impostorWord: "كباب" },
    { word: "شاورما", impostorWord: "كفتة" },
    { word: "كباب", impostorWord: "كفتة" },
    { word: "كفتة", impostorWord: "كباب" },
    { word: "سمك مشوي", impostorWord: "جمبري" },
    { word: "فسيخ", impostorWord: "سردين" },
    { word: "رقاق", impostorWord: "فطير" },
    { word: "فطير", impostorWord: "رقاق" },
    { word: "عيش بالسمن", impostorWord: "فطير مشلتت" },
    { word: "بامية", impostorWord: "ملوخية" },
    { word: "بطاطس محمرة", impostorWord: "شيبسي" },
    { word: "شوربة لسان عصفور", impostorWord: "شوربة عدس" },
    { word: "عدس", impostorWord: "فول" },
    { word: "ممبار", impostorWord: "محشي" },
    { word: "فتة", impostorWord: "فتة مكدوس" },
    { word: "حمام", impostorWord: "فراخ" },
    { word: "فراخ مشوية", impostorWord: "بط" },
    { word: "لحمة فرم", impostorWord: "كفتة" },
    { word: "كوارع", impostorWord: "لحمة" },
    { word: "مخ", impostorWord: "كبدة" },
    { word: "سحلب", impostorWord: "خامر" },
    { word: "بليلة", impostorWord: "عصيدة" },
    { word: "عصيدة", impostorWord: "بليلة" },
    { word: "جبنة قريش", impostorWord: "جبنة بيضاء" },
    { word: "طعمية شامية", impostorWord: "فول" },
    { word: "بسبوسة", impostorWord: "كنافة" },
    { word: "مكرونة", impostorWord: "رز" },
    { word: "رز", impostorWord: "مكرونة" },
    { word: "شكشوكة", impostorWord: "بيض" },
    { word: "بيض", impostorWord: "أومليت" },
    { word: "بطاطس", impostorWord: "بطاطس محمرة" },
    { word: "سلطة", impostorWord: "طحينة" },
    { word: "طحينة", impostorWord: "حمص" },
    { word: "حمص", impostorWord: "طحينة" },
    { word: "باذنجان", impostorWord: "كوسة" },
    { word: "كوسة", impostorWord: "باذنجان" },
    { word: "سبانخ", impostorWord: "بامية" },
    { word: "دقيق", impostorWord: "عيش" },
    { word: "عيش بلدي", impostorWord: "عيش شامي" },
    { word: "عيش فينو", impostorWord: "توست" },
    { word: "شيش طاووق", impostorWord: "كباب" },
    { word: "مولوخية بالأرانب", impostorWord: "ملوخية" },
    { word: "بط", impostorWord: "فراخ" },
    { word: "لانشون", impostorWord: "سوسيس" },
    { word: "سوسيس", impostorWord: "لانشون" },
    { word: "بيتزا", impostorWord: "بيتزا مصري" },
  ],
  egyptian_sweets: [
    { word: "تورتة", impostorWord: "بسبوسة" },
    { word: "جاتوه", impostorWord: "كحك" },
    { word: "كنافة", impostorWord: "مهلبية" },
    { word: "قطايف", impostorWord: "زنود الست" },
    { word: "بسبوسة", impostorWord: "هريسة" },
    { word: "مهلبية", impostorWord: "سحلب" },
    { word: "أرز باللبن", impostorWord: "أم علي" },
    { word: "قشطة", impostorWord: "عسل" },
    { word: "حلاوة طحينية", impostorWord: "حلقوم" },
    { word: "حلاوة جبن", impostorWord: "ملبن" },
    { word: "ملبن", impostorWord: "مصاصة" },
    { word: "سحلب", impostorWord: "خامر" },
    { word: "بلح الشام", impostorWord: "لقيمات" },
    { word: "زنود الست", impostorWord: "عوامة" },
    { word: "غريبة", impostorWord: "بيتي فور" },
    { word: "كحك", impostorWord: "غريبة" },
    { word: "مشبك", impostorWord: "بلح الشام" },
    { word: "لقيمات", impostorWord: "دونات" },
    { word: "عوامة", impostorWord: "مفروكة" },
    { word: "آيس كريم", impostorWord: "مولتو" },
    { word: "مولتو", impostorWord: "كرواسون" },
    { word: "دونات", impostorWord: "كرواسون" },
    { word: "حلوى المولد", impostorWord: "علب" },
    { word: "فستق", impostorWord: "كاجو" },
    { word: "لوز", impostorWord: "جوز" },
    { word: "بندق", impostorWord: "لوز" },
    { word: "عسل", impostorWord: "مربى" },
    { word: "مربى", impostorWord: "دبس تمر" },
    { word: "راحة", impostorWord: "حلاوة طحينية" },
    { word: "حلقوم", impostorWord: "راحة" },
    { word: "أم علي", impostorWord: "أرز باللبن" },
    { word: "شوكولاتة", impostorWord: "آيس كريم" },
    { word: "كادبوري", impostorWord: "شوكولاتة" },
    { word: "علب", impostorWord: "لب" },
    { word: "هريسة", impostorWord: "بسبوسة" },
    { word: "خامر", impostorWord: "سحلب" },
    { word: "مفروكة", impostorWord: "عوامة" },
    { word: "كرواسون", impostorWord: "مولتو" },
    { word: "بيتي فور", impostorWord: "كحك" },
    { word: "دبس تمر", impostorWord: "عسل" },
    { word: "كنافة بالقشطة", impostorWord: "قطايف" },
    { word: "كنافة نابلسية", impostorWord: "مهلبية" },
    { word: "بسبوسة نوتيلا", impostorWord: "هريسة" },
    { word: "قطايف محشية", impostorWord: "زنود الست" },
    { word: "كحك عيد", impostorWord: "غريبة" },
    { word: "حلاوة مش", impostorWord: "حلقوم" },
    { word: "مصاصة", impostorWord: "ملبن" },
    { word: "كاجو", impostorWord: "فستق" },
    { word: "جوز", impostorWord: "بندق" },
    { word: "لب", impostorWord: "علب" },
    { word: "كريمة", impostorWord: "قشطة" },
  ],
  egyptian_celebrities: [
    { word: "عادل إمام", impostorWord: "محمود عبد العزيز" },
    { word: "محمود عبد العزيز", impostorWord: "أحمد زكي" },
    { word: "أحمد زكي", impostorWord: "محمود ياسين" },
    { word: "محمود ياسين", impostorWord: "نور الشريف" },
    { word: "نور الشريف", impostorWord: "محمود عبد العزيز" },
    { word: "يسرا", impostorWord: "هند صبري" },
    { word: "منى زكي", impostorWord: "هند صبري" },
    { word: "هند صبري", impostorWord: "منى زكي" },
    { word: "أحمد حلمي", impostorWord: "كريم عبد العزيز" },
    { word: "كريم عبد العزيز", impostorWord: "أحمد عز" },
    { word: "محمد هنيدي", impostorWord: "أحمد مكي" },
    { word: "أحمد مكي", impostorWord: "محمد هنيدي" },
    { word: "عمرو دياب", impostorWord: "تامر حسني" },
    { word: "عمر دياب", impostorWord: "محمد منير" },
    { word: "تامر حسني", impostorWord: "محمد منير" },
    { word: "محمد منير", impostorWord: "حميد الشاعري" },
    { word: "أم كلثوم", impostorWord: "فيروز" },
    { word: "فيروز", impostorWord: "أم كلثوم" },
    { word: "عبد الحليم", impostorWord: "فريد الأطرش" },
    { word: "فريد الأطرش", impostorWord: "عبد الحليم" },
    { word: "شريف منير", impostorWord: "أحمد السقا" },
    { word: "أحمد السقا", impostorWord: "كريم عبد العزيز" },
    { word: "ياسمين عبد العزيز", impostorWord: "منى زكي" },
    { word: "غادة عبد الرازق", impostorWord: "دنيا سمير غانم" },
    { word: "دنيا سمير غانم", impostorWord: "ياسمين عبد العزيز" },
    { word: "نيللي كريم", impostorWord: "بسمة" },
    { word: "أحمد عز", impostorWord: "يوسف الشريف" },
    { word: "يوسف الشريف", impostorWord: "أحمد عز" },
    { word: "محمد رمضان", impostorWord: "أحمد السقا" },
    { word: "عمرو يوسف", impostorWord: "أحمد الفيشاوي" },
    { word: "أحمد الفيشاوي", impostorWord: "عمرو يوسف" },
    { word: "بوسي", impostorWord: "شيرين" },
    { word: "شيرين", impostorWord: "أصالة" },
    { word: "أصالة", impostorWord: "إليسا" },
    { word: "إليسا", impostorWord: "نانسي عجرم" },
    { word: "نانسي عجرم", impostorWord: "هيفاء وهبي" },
    { word: "هيفاء وهبي", impostorWord: "نانسي عجرم" },
    { word: "محمد صلاح", impostorWord: "أبو تريكة" },
    { word: "أبو تريكة", impostorWord: "محمد صلاح" },
    { word: "باسم يوسف", impostorWord: "عمرو أديب" },
    { word: "عمرو أديب", impostorWord: "لميس الحديدي" },
    { word: "لميس الحديدي", impostorWord: "منى الشاذلي" },
    { word: "منى الشاذلي", impostorWord: "إسعاد يونس" },
    { word: "إسعاد يونس", impostorWord: "منى الشاذلي" },
    { word: "فهمي عبد الحميد", impostorWord: "يحيى الفخراني" },
    { word: "يحيى الفخراني", impostorWord: "فهمي عبد الحميد" },
    { word: "ليلى علوي", impostorWord: "نبيلة عبيد" },
    { word: "نبيلة عبيد", impostorWord: "سهير رمزي" },
    { word: "سعاد حسني", impostorWord: "نبيلة عبيد" },
    { word: "فاتن حمامة", impostorWord: "سعاد حسني" },
    { word: "رامز جلال", impostorWord: "أحمد حلمي" },
    { word: "علا غانم", impostorWord: "هالة صدقي" },
    { word: "هالة صدقي", impostorWord: "علا غانم" },
  ],
};
