export const rawPrompts = [
  ["تفاحة زجاجية بداخلها مجرة تلمع", "macro photography of a glowing hyper-detailed galaxy swirling inside a transparent glass apple, deep space background, cinematic lighting, 8k resolution, masterpiece"],
  ["أخطبوط ميكانيكي يعزف على بيانو من العظام", "highly detailed steampunk mechanical octopus playing a grand piano made entirely of glowing white bones, dark cinematic atmosphere, photorealistic 8k, unreal engine 5 render"],
  ["فنجان قهوة يشتعل بالنار ويحتوي على جليد", "macro photography of a ceramic coffee cup containing a mesmerizing mix of burning fire flames and solid frozen ice cubes simultaneously, dramatic lighting, 8k, highly detailed"],
  ["دراجة نارية مستقبلية من عظام ديناصور", "futuristic cyberpunk neon motorcycle built completely from giant glowing dinosaur T-rex bones, glowing neon lights, dark street background, 8k resolution, photorealistic"],
  ["وردة أوراقها دوائر إلكترونية تضيء باللون الأزرق", "a blooming rose with glowing blue futuristic circuit board petals, dark background, cybernetic nature, highly detailed, macro photography, 8k"],
  ["قطة سوداء بأجنحة خفاش وذيل عقرب", "terrifying yet majestic black cat with giant bat wings and a glowing scorpion tail, perched on a gothic gargoyle, full moon night, photorealistic, 8k"],
  ["حذاء رياضي زجاجي بداخله قروش تسبح", "transparent glass sneaker filled with blue ocean water, tiny realistic sharks swimming inside the shoe, studio lighting, hyper-realistic, macro 8k"],
  ["يد بشرية تنبت كشجرة بلوط من الأرض", "surreal image of a human hand growing directly from dark soil, transforming into a giant ancient oak tree with green leaves, cinematic lighting, photorealistic"],
  ["ساعة يد تذوب مثل الآيس كريم تحت الشمس", "luxury wristwatch melting exactly like dripping vanilla ice cream under a bright hot sun, surrealism art, highly detailed, vivid colors, 8k"],
  ["ثلاجة مفتوحة بداخلها غابة استوائية كاملة", "open kitchen refrigerator containing a massive deep tropical jungle inside with glowing sunlight beams, photorealistic surrealism, highly detailed 8k"],
  ["كتاب سحري مفتوح ينزف حبراً أحمر لامعاً", "ancient open magic spell book bleeding thick glowing red ink from its blank pages, dark magical atmosphere, photorealistic, 8k resolution"],
  ["سيارة كلاسيكية تطير بأجنحة نسر عملاقة", "vintage 1950s classic car flying high in the sky with giant realistic eagle wings, fluffy white clouds, photorealistic 8k, majestic cinematic lighting"],
  ["تلفاز قديم يعرض أحلاماً مضيئة تخرج من الشاشة", "vintage retro CRT tv sitting in a dark room, emitting glowing 3d holographic dreams floating out of the screen into the room, cinematic 8k"],
  ["فيل صغير جداً بحجم نملة يقف على عملة معدنية", "macro photography of a tiny microscopic realistic elephant the exact size of an ant standing perfectly on a shiny copper coin, hyper-detailed, 8k"],
  ["مدينة مستقبلية كاملة داخل زجاجة عطر", "entire sprawling futuristic cyberpunk city with flying cars contained inside a small glass perfume bottle, glowing lights, macro photography, 8k"],
  ["شريحة بيتزا ضخمة تطفو في الفضاء الخارجي", "giant delicious pepperoni pizza slice floating majestically in deep outer space surrounded by glowing stars and planets, photorealistic 8k"],
  ["أسد مهيب مصنوع بالكامل من الزجاج الشفاف", "majestic roaring lion made entirely of completely transparent clear glass, refracting light, standing on a rock, photorealistic 8k, cinematic lighting"],
  ["نهر يتدفق بالذهب السائل اللامع في غابة", "beautiful forest landscape with a river flowing with bright glowing liquid gold instead of water, ethereal fantasy lighting, photorealistic 8k"],
  ["عنكبوت آلي يغزل شبكة من أشعة الليزر الحمراء", "futuristic robotic spider weaving a complex spider web made entirely of glowing red laser beams, dark background, photorealistic 8k, cyberpunk"],
  ["جزيرة استوائية تطفو على ظهر سلحفاة عملاقة", "massive floating tropical island with waterfalls and palm trees resting on the shell of a giant flying sea turtle in the sky, photorealistic 8k"],
  ["قمر كامل مصنوع من الجبن السويسري الذائب", "close up shot of the full moon in the night sky, but the moon is made entirely of delicious melting yellow swiss cheese with holes, photorealistic"],
  ["قلعة ضخمة مبنية بالكامل من أوراق اللعب", "massive epic medieval castle built completely out of giant playing cards, standing in a green field, highly detailed, photorealistic 8k"],
  ["سحابة رمادية تمطر عملات ذهبية ونقوداً", "dark stormy cloud in the sky raining bright shiny golden coins and green money bills instead of water, photorealistic 8k, cinematic lighting"],
  ["جبل بركاني يثور ويقذف مكعبات ثلج وجليد", "massive volcano erupting violently, but spewing white snow and giant ice cubes instead of hot lava, winter landscape, photorealistic 8k"],
  ["قرش أبيض يطير في السماء مربوطاً ببالونات ملونة", "great white shark floating peacefully in the blue sky, suspended by hundreds of colorful helium balloons tied to its back, surreal photorealistic 8k"],
  ["شاشة هاتف يخرج منها مخلب وحش ثلاثي الأبعاد", "modern smartphone lying on a table, with a terrifying realistic 3d monster claw reaching out directly from the screen, cinematic dark lighting, 8k"],
  ["رجل يرتدي بدلة أنيقة برأس كاميرا تصوير قديمة", "man wearing a sharp tailored business suit, but his head is a giant vintage film camera, walking in a modern city, photorealistic 8k"],
  ["شجرة غامضة تثمر مصابيح مضيئة بدلاً من الفاكهة", "mystical ancient tree in a dark forest, growing bright glowing electric lightbulbs hanging from its branches instead of fruit, photorealistic 8k"],
  ["مظلة تحمي من المطر وتعكس مجرة تحتها", "person holding an umbrella in rain, but the underside of the umbrella shows a glowing endless galaxy of stars, surreal cinematic photorealistic 8k"],
  ["قطار بخاري يخترق سحباً من غزل البنات الوردي", "classic steam train driving through a magical landscape made of fluffy pink cotton candy clouds, vibrant colors, photorealistic 8k, fantasy"],
  ["عين بشرية عملاقة وواقعية في قلب زهرة عباد الشمس", "macro shot of a bright yellow sunflower, but the center of the flower is a giant highly realistic human blue eye looking directly at the camera, 8k"],
  ["بيانو خشبي ضخم يخرج منه دخان ملون وكثيف", "elegant wooden grand piano playing by itself, emitting thick clouds of vibrant rainbow-colored smoke from its strings, dramatic lighting, photorealistic 8k"],
  ["دراجة هوائية عجلاتها عبارة عن شرائح بطيخ ضخمة", "classic bicycle parked on a street, but both of its wheels are massive fresh juicy watermelon slices, surreal highly detailed photorealistic 8k"],
  ["فراشة أجنحتها مصنوعة من لهب ناري متوهج", "beautiful butterfly flying in the dark, its wings made entirely of bright glowing orange and red fire flames, highly detailed photorealistic 8k"],
  ["تمثال الحرية يرتدي سماعات رأس عصرية ضخمة", "the statue of liberty in new york, wearing giant modern neon gaming headphones over its ears, cyberpunk elements, photorealistic 8k"],
  ["بومة ترتدي نظارات طبية وتقرأ في مكتبة قديمة", "wise old owl wearing round reading glasses, sitting on a wooden desk reading an ancient open book in a dusty old library, photorealistic 8k"],
  ["بطريق يمشي بصعوبة على رمال الصحراء الحارقة", "a confused emperor penguin walking on hot orange sand dunes in the middle of the sahara desert under a blazing sun, photorealistic 8k"],
  ["مروحية عسكرية مصنوعة بالكامل من خشب منحوت", "military helicopter flying in the sky, but the entire vehicle is built from intricately carved polished brown wood, highly detailed photorealistic 8k"],
  ["سلم حجري لا نهائي يصعد نحو قمر عملاق", "endless ancient stone staircase reaching up endlessly into the dark night sky towards a massive glowing full moon, ethereal cinematic photorealistic 8k"],
  ["نحلة ميكانيكية دقيقة تعمل بالتروس والنحاس", "macro photography of a highly detailed mechanical steampunk bee made of brass gears, cogs, and glass wings, resting on a flower, photorealistic 8k"],
  ["قارب ورق اوريغامي يبحر في فنجان قهوة عميق", "small white origami paper boat sailing perfectly on the dark liquid surface of black coffee inside a white ceramic cup, macro photography 8k"],
  ["مدينة ملاهي مهجورة تحت الماء تضيء في الظلام", "abandoned creepy amusement park sunken deep underwater, rusted ferris wheel glowing with eerie green bioluminescent lights, photorealistic 8k"],
  ["كرسي خشبي قديم يطير بصواريخ نفاثة مشتعلة", "simple old wooden dining chair flying high in the sky, powered by two massive futuristic burning jet rockets attached to its back, photorealistic 8k"],
  ["قرد يرتدي نظارة شمسية ويعزف جيتاراً كهربائياً", "cool chimpanzee wearing dark sunglasses, rocking out playing a red electric guitar on a concert stage with laser lights, photorealistic 8k"],
  ["باب خشبي قائم بذاته مفتوح في وسط المحيط", "freestanding old wooden door standing upright in the exact middle of a calm blue ocean, opened slightly revealing a glowing light, photorealistic 8k"],
  ["عين إعصار عملاق تكشف عن مجرة بداخلها", "massive violent tornado funnel cloud, but looking directly into the eye reveals a calm glowing colorful outer space galaxy, photorealistic 8k"],
  ["طبق طائر فضائي يهبط في غابة استوائية خضراء", "classic metallic ufo flying saucer spaceship landing peacefully in a dense green tropical rainforest, glowing blue lights, cinematic photorealistic 8k"],
  ["وحش بحري ضخم مصنوع من عبوات البلاستيك الفارغة", "terrifying giant sea monster emerging from the ocean, made entirely out of thousands of crushed recycled clear plastic water bottles, photorealistic 8k"],
  ["شمس زرقاء ساطعة تغرب خلف جبال مغطاة بالثلوج", "breathtaking landscape showing a glowing bright blue sun setting behind majestic high snow-capped mountains, alien planet vibe, photorealistic 8k"],
  ["قلب بشري نابض مصنوع بالكامل من تروس ميكانيكية", "highly detailed beating human heart shape made completely out of intricate interlocking brass and steel steampunk clockwork gears, photorealistic 8k"],
  ["برغر ضخم تتوسطه مجرة بدلاً من اللحم", "giant delicious hamburger, but instead of a meat patty, there is a glowing swirling purple outer space galaxy in the middle, photorealistic 8k"],
  ["سلحفاة تحمل ناطحات سحاب مدينة نيويورك على ظهرها", "giant sea turtle swimming in the ocean, carrying the entire glowing skyline and skyscrapers of new york city on its shell, photorealistic 8k"],
  ["شبح لطيف يرتدي قبعة ساحر ويشرب الشاي", "cute transparent glowing white ghost wearing a tall purple wizard hat, gently sipping tea from a tiny elegant porcelain cup, photorealistic 8k"],
  ["نمر من الثلج الكريستالي يمشي في غابة نارية", "majestic tiger made entirely of glowing blue crystal ice walking fiercely through a dense forest that is on fire, dramatic contrast, photorealistic 8k"],
  ["مصباح علاء الدين يخرج منه دخان يشكل تنيناً", "ancient golden magic lamp sitting on sand, emitting glowing purple smoke that perfectly forms the shape of a fierce dragon, photorealistic 8k"],
  ["قلم رصاص يرسم باباً حقيقياً يفتح لعالم آخر", "giant wooden pencil drawing a realistic wooden door on a white wall, and the door is slightly open revealing a glowing fantasy forest, photorealistic 8k"],
  ["خيمة سيرك تطير في السماء مدفوعة ببالونات هواء", "massive red and white striped circus tent floating high in the sky, lifted by hundreds of giant colorful hot air balloons, photorealistic 8k"],
  ["غواصة ميكانيكية تستكشف أطلال كوكب المريخ", "futuristic rusty steampunk submarine floating over the dry red dusty ruins of an ancient city on the planet Mars, photorealistic 8k, cinematic"],
  ["بيضة ذهبية ضخمة تنشق ليخرج منها ضوء ساطع", "massive solid gold egg cracking open in a dark cave, emitting blinding rays of pure white heavenly light from the cracks, photorealistic 8k"],
  ["حصان يركض على سطح الماء المضاء بالنجوم", "majestic white horse galloping perfectly on the surface of a calm mirror-like lake reflecting a galaxy of glowing stars, photorealistic 8k"],
  ["سيف سحري مغروس في صخرة ينبض بالطاقة الزرقاء", "ancient glowing magical sword stuck deep in a giant stone, pulsating with crackling blue lightning energy, dark misty forest, photorealistic 8k"],
  ["منزل شجرة مبني على فطر عملاق متوهج", "cozy wooden treehouse built on top of a massive glowing neon bioluminescent mushroom in a magical dark forest, photorealistic 8k, highly detailed"],
  ["رجل آلي حزين يجلس تحت المطر يحمل مظلة حمراء", "sad rusty futuristic robot sitting on a city bench in pouring rain, holding a bright red umbrella, cyberpunk city background, photorealistic 8k"],
  ["عربة تسوق مليئة بالغيوم الملونة المضيئة", "metal grocery shopping cart sitting in a parking lot, overflowing with glowing fluffy colorful rainbow clouds, surreal photorealistic 8k"],
  ["ديناصور تي ريكس يرتدي بدلة فضاء في المريخ", "giant realistic T-Rex dinosaur wearing a highly detailed modern white astronaut space suit, standing on the red dirt of Mars, photorealistic 8k"],
  ["شطرنج حيث القطع جنود حقيقيون صغار جداً", "macro photography of a wooden chessboard, but the chess pieces are highly detailed tiny living medieval knights and kings, photorealistic 8k"],
  ["بوصلة قديمة تشير عقاربها إلى قلب نابض", "vintage brass pocket compass, but instead of north, the needle is pointing directly at a small glowing red beating heart in the center, photorealistic 8k"],
  ["غابة من الكريستال الشفاف تنعكس فيها الشمس", "beautiful alien forest where all the trees and leaves are made of perfectly clear transparent crystal glass, refracting bright sunlight, photorealistic 8k"],
  ["شاشة كمبيوتر تتدفق منها شلالات مياه حقيقية", "old desktop computer monitor on a desk, with a massive raging waterfall of real blue water pouring violently out of the screen, photorealistic 8k"],
  ["كاميرا تصوير تلتقط صورة فتخرج منها طيور حية", "vintage camera taking a photo, but instead of a flash, a flock of beautiful colorful living birds bursts out of the lens, photorealistic 8k"],
  ["حوت أزرق ضخم يسبح بين ناطحات سحاب في الضباب", "massive majestic blue whale swimming gracefully through the air between giant modern skyscrapers in a dense foggy city, surreal photorealistic 8k"],
  ["كوب شاي صغير بداخله عاصفة رعدية وبرق", "macro shot of a delicate porcelain teacup, containing a violent swirling thunderstorm with dark clouds and glowing lightning bolts inside the cup, 8k"],
  ["عقد من اللؤلؤ كل لؤلؤة تحتوي على كوكب مختلف", "beautiful pearl necklace resting on black velvet, but inside every single pearl is a highly detailed tiny rotating planet or galaxy, photorealistic 8k"],
  ["سيارة إطفاء تطلق ألوان الطلاء بدلاً من الماء", "red fire truck spraying massive thick streams of vibrant rainbow liquid paint instead of water onto a burning grey building, photorealistic 8k"],
  ["جيتار صوتي مصنوع من الجليد يذوب ببطء", "beautiful acoustic guitar carved completely out of crystal clear ice, slowly melting into a puddle of water under a spotlight, photorealistic 8k"],
  ["قلعة رملية عملاقة في الصحراء تسكنها عقارب ذهبية", "massive detailed medieval sandcastle built in the sahara desert, guarded by giant glowing golden scorpions, epic cinematic lighting, photorealistic 8k"],
  ["تمثال فرعوني يرتدي نظارة واقع افتراضي", "ancient ancient egyptian pharaoh statue made of gold, wearing a modern sleek VR virtual reality headset glowing with blue lights, photorealistic 8k"],
  ["سلم موسيقي يطفو في الهواء وتعزفه عصافير", "floating glowing musical notes and staff lines in the sky, being played by hundreds of tiny colorful singing birds sitting on the lines, photorealistic 8k"],
  ["مكعب روبيك حيث كل مربع يمثل فصلاً من السنة", "rubiks cube where each colored square shows a highly detailed tiny 3d diorama of winter snow, spring flowers, summer sun, and autumn leaves, 8k"],
  ["سجادة سحرية تطير فوق مدينة مستقبلية مضيئة", "ancient woven magic carpet flying high above a sprawling glowing cyberpunk megacity with neon lights and flying cars, photorealistic 8k"],
  ["حصالة نقود على شكل خنزير تبتلع سبائك ذهب", "ceramic pink piggy bank magically expanding its mouth to swallow massive heavy glowing solid gold bars, highly detailed photorealistic 8k"],
  ["مفتاح قديم يفتح شقاً في نسيج الفضاء والزمن", "glowing ancient brass key turning in mid-air, ripping open a glowing purple portal rift in the fabric of space and time, cinematic photorealistic 8k"],
  ["دولاب ملابس يحتوي على سلم يؤدي إلى القمر", "open wooden wardrobe closet, but instead of clothes, it reveals an endless wooden ladder climbing up into a starry night sky towards the moon, 8k"],
  ["أرجوحة مربوطة بين قرني قمر هلال ضخم", "childs wooden swing suspended by ropes tied between the two glowing tips of a massive crescent moon in the night sky, surreal photorealistic 8k"],
  ["منبه يطلق فقاعات صابون بدلاً من الصوت المزعج", "classic twin bell alarm clock ringing, but instead of sound waves, it is shooting hundreds of iridescent rainbow soap bubbles into the room, 8k"],
  ["كرات بلياردو تمثل الكواكب تصطدم بعصا ليزر", "billiard pool table where the balls are highly detailed realistic planets like Jupiter and Mars, being struck by a glowing neon laser pool cue, 8k"],
  ["منطاد هواء ساخن محركه تنين ناري يتنفس", "steampunk hot air balloon where the heat source is a small highly detailed red dragon continuously breathing fire into the balloon, photorealistic 8k"],
  ["فارس مدرع يمتطي دراجة نارية هارلي ديفيدسون", "medieval knight in full shining steel armor riding a loud roaring classic harley davidson motorcycle down a dirty muddy battlefield, photorealistic 8k"],
  ["صندوق بريد خشبي تخرج منه رسائل تحولت لطيور", "old rusty mailbox opening, and dozens of paper envelopes fly out, magically transforming into white doves mid-air, photorealistic 8k"],
  ["قطعة شطرنج للملك مصنوعة من الجليد ضد ملك من نار", "macro shot of a chessboard, a white king piece made of freezing crystal ice fighting a black king piece made of roaring fire flames, photorealistic 8k"],
  ["مرآة تعاكس الحقيقة وتظهر شخصية وحشية", "elegant young woman looking into a vintage mirror, but the mirror reflection shows a terrifying glowing demon looking back at her, photorealistic 8k"],
  ["مغناطيس عملاق يجذب النجوم من السماء ليلاً", "massive red horseshoe magnet pointed at the night sky, pulling thousands of glowing white stars down from space like metal dust, photorealistic 8k"],
  ["نبع ماء حار يخرج منه حبر ألوان مائية", "geyser erupting from the rocky ground, but instead of water, it shoots a massive explosion of vibrant colorful watercolor paint, photorealistic 8k"],
  ["عالم نباتات يزرع شجرة من شرائح إلكترونية", "scientist in a lab coat gently watering a small glowing plant growing in a pot, but the plant is made of green computer motherboards and wires, 8k"],
  ["بوصلة ذهبية تشير لجزيرة تطفو فوق السحاب", "close up of an ornate golden compass, with its glowing needle pointing directly towards a massive floating island hiding above the clouds, 8k"],
  ["حذاء تزلج عجلاته مصنوعة من مناشير دائرية", "punk rock inline roller skates, but the wheels are sharp spinning metal circular saw blades cutting into the concrete floor, sparks flying, 8k"],
  ["شلال يتدفق بالعكس من الأرض إلى السماء", "massive majestic waterfall, but the roaring water is defying gravity and flowing rapidly upwards from the ground into the clouds, photorealistic 8k"],
  ["فرشاة أسنان ضخمة تنظف أسنان تمثال حجري كبير", "giant yellow toothbrush being used to brush the massive stone teeth of an ancient colossal gargoyle statue, surreal humor, photorealistic 8k"],
  ["قنبلة موقوتة مليئة ببتلات الورود الناعمة", "glass time bomb ticking down to zero, but the explosive inside is just thousands of soft red rose petals ready to burst beautifully, photorealistic 8k"],
  ["كعكة زفاف مبنية كقلعة يهاجمها تنين سكر", "elegant multi-tiered wedding cake designed like a castle, being attacked by a highly detailed edible dragon made of red spun sugar, photorealistic 8k"],
  ["طائر مصنوع من الزجاج ينشر ضوء الغروب", "beautiful glass bird flying in the sky, scattering the golden warm light of a glowing sunset through its transparent wings, photorealistic 8k"],
  ["جمل بحدبتين يحمل ناطحتي سحاب فوقه", "surreal realistic camel walking in the desert, carrying two massive highly detailed futuristic skyscrapers on its back instead of humps, photorealistic 8k"],
  ["محطة وقود في الفضاء تبيع غبار النجوم", "retro 1950s gas station floating in deep outer space, with neon signs selling glowing stardust to flying spaceships, cyberpunk 8k"],
  ["سفينة قراصنة تبحر في بحر من الكريستال السائل", "epic ancient pirate ship sailing smoothly on an ocean made entirely of glowing liquid diamonds and bright crystals, cinematic lighting 8k"],
  ["رجل ثلج يجلس داخل ساونا خشبية ويقرأ كتابا", "cheerful happy snowman sitting comfortably inside a hot steaming wooden sauna, reading a book without melting, surrealism, highly detailed 8k"],
  ["هاتف ذكي قديم تنمو منه جذور شجرة", "old broken vintage smartphone lying on grass, with ancient thick tree roots growing deeply out of its cracked screen, photorealistic 8k"],
  ["عازف كمان بلا رأس يعزف في غابة مظلمة", "headless musician in an elegant suit playing a glowing ghostly violin in a dark misty forest at midnight, hauntingly beautiful, photorealistic 8k"],
  ["دودة كتب حقيقية تأكل المعرفة وتضيء", "macro shot of a literal tiny glowing bookworm crawling across old pages, glowing brighter as it magically consumes the ink, photorealistic 8k"],
  ["منطاد على شكل قلب بشري ينبض في السماء", "massive highly realistic anatomically correct human heart floating in the sky like a hot air balloon, dripping light, surreal 8k"],
  ["خاتم زواج يحتجز إعصاراً بداخله", "macro photography of a shiny diamond engagement ring, but instead of a diamond, there is a tiny violent raging tornado trapped inside, 8k"],
  ["فنجان شاي يفيض بأمواج البحر وسفن صغيرة", "delicate porcelain teacup overflowing with crashing blue ocean waves, with tiny detailed 18th century ships sailing inside the cup, 8k"],
  ["مدينة كاملة مبنية على ظهر حلزون عملاق", "massive cyberpunk futuristic city with neon lights built entirely on the spiraling shell of a giant realistic garden snail, photorealistic 8k"],
  ["خزانة ملابس بابها يفتح على قاع المحيط", "old wooden wardrobe door opened, revealing a terrifying view of the deep dark ocean floor with glowing jellyfish swimming inside, 8k"],
  ["نمر يرتدي نظارة شمسية ويشرب عصير الليمون", "cool relaxed tiger wearing black aviator sunglasses, sitting on a beach chair drinking a yellow lemonade with a straw, highly detailed 8k"],
  ["سيارة إسعاف تطير بأجنحة ملائكية", "modern red and white ambulance flying rapidly through the clouds, propelled by giant glowing majestic white angel wings, photorealistic 8k"],
  ["طاولة بلياردو مصنوعة من كوكب المشتري", "billiard pool table where the green felt is replaced by the swirling orange gas clouds of the planet Jupiter, playing with meteorites, 8k"],
  ["سلحفاة ميكانيكية تعمل بالبخار والفحم", "highly detailed steampunk tortoise made of brass and copper pipes, with thick black coal steam puffing from its metal shell, photorealistic 8k"],
  ["كرسي متحرك مزود بصواريخ فضائية", "medical wheelchair aggressively flying through the air, modified with two massive roaring spaceship jet engines strapped to the sides, 8k"],
  ["جيتار أوتاره مصنوعة من أشعة الليزر", "electric guitar where the strings are glowing bright neon laser beams, being played on a dark stage, cyberpunk aesthetic, 8k"],
  ["عنكبوت يغزل شبكة من الذهب الخالص", "macro photography of a dark spider weaving an incredibly intricate web made of thick glowing solid gold threads, photorealistic 8k"],
  ["مكواة ملابس تطلق غيوماً رعدية", "laundry iron pressing a shirt, but instead of white steam, it is emitting dark stormy thunderclouds and tiny lightning bolts, 8k"],
  ["طائر نعام يرتدي حذاء تزلج سريع", "realistic ostrich aggressively rolling down a city street wearing modern professional inline speed skates, motion blur, photorealistic 8k"],
  ["شجرة تفاح تثمر عيوناً بشرية زرقاء", "ancient dark apple tree, but instead of fruit, it grows highly realistic bright blue human eyes looking around, surreal horror, photorealistic 8k"],
  ["مظلة شفافة تحمي من النيازك المتساقطة", "person holding a glowing clear energy umbrella, calmly deflecting burning red meteorites falling from an apocalyptic sky, photorealistic 8k"],
  ["ساعة رملية تتدفق فيها النجوم بدلا من الرمل", "elegant vintage hourglass, but instead of sand, it is filled with thousands of tiny glowing white stars pouring into a galaxy at the bottom, 8k"],
  ["زجاجة ماء تحتوي على ديناصور مصغر", "clear plastic water bottle resting on a desk, containing a tiny highly detailed living T-rex dinosaur swimming inside the water, 8k"],
  ["تمساح يعزف على بيانو في قاع النهر", "large green crocodile sitting underwater at the bottom of a river, elegantly playing a grand piano covered in moss, photorealistic 8k"],
  ["شاشة سينما تعرض المستقبل الحقيقي", "crowded movie theater where the bright screen is projecting a realistic glowing 3d hologram of a futuristic cyberpunk city, photorealistic 8k"],
  ["بيت من الطوب مبني على سحابة ممطرة", "cozy red brick house built directly on top of a dark grey rain cloud floating high in the sky, raining below, surreal photorealistic 8k"],
  ["عصفور ميكانيكي يبني عشاً من الأسلاك", "steampunk mechanical bird made of gears and brass, building a complex nest entirely out of colorful electric wires and motherboards, 8k"],
  ["قبعة ساحر يخرج منها مجرة حلزونية", "classic black velvet magician top hat sitting on a table, emitting a massive glowing purple spiral galaxy floating upwards, 8k"],
  ["فستان سهرة مصنوع من شلال مياه حقيقي", "elegant fashion model walking a runway, wearing a breathtaking dress made entirely of continuously flowing real blue waterfall water, 8k"],
  ["مصباح شارع يضيء بأشعة القمر المجمدة", "old victorian street lamp emitting a glowing pale blue light that freezes the air around it into intricate ice crystals, photorealistic 8k"],
  ["محرك سيارة ينبض كقلب بشري", "highly detailed greasy car engine block pulsating and beating organically like a massive human heart, dark surreal realism, 8k"],
  ["نحلة عملاقة تحمل قطار ركاب", "giant hyper-realistic fuzzy yellow bee flying through the sky, carrying a full-sized modern passenger train in its legs, photorealistic 8k"],
  ["غابة من الأقلام الرصاص العملاقة", "surreal landscape of a vast forest where all the trees are actually giant yellow wooden pencils with pink erasers touching the sky, 8k"],
  ["مكتبة كتبها تطير كالطيور", "ancient grand library where thousands of open books are flapping their pages and flying around the room like a flock of white birds, 8k"],
  ["كوب قهوة يبتلع من يشربه", "surreal horrifying image of a giant coffee cup growing sharp teeth and aggressively swallowing a man trying to drink from it, photorealistic 8k"],
  ["عقدة حبل مستحيلة الفك في الفضاء", "glowing thick rope tied in an impossible infinite knot, floating in the dark void of deep space surrounded by distant stars, 8k"],
  ["حذاء سندريلا الزجاجي مكسور وينزف", "beautiful clear glass slipper shattered on a dark stone floor, dripping bright glowing red liquid, dramatic moody lighting, photorealistic 8k"],
  ["بطريق يرتدي درع فارس في العصور الوسطى", "cute emperor penguin standing bravely on snow, wearing a full suit of shiny steel medieval knight armor holding a tiny sword, 8k"],
  ["بئر ماء عميق يؤدي إلى سطح الشمس", "looking straight down into a dark stone well, but the bottom reveals the terrifying blinding bright burning surface of the sun, 8k"],
  ["تنين ناري ينام داخل مدفأة منزلية", "cozy living room with a fireplace, but instead of logs, a small highly detailed red fire dragon is curled up sleeping inside the flames, 8k"],
  ["مفتاح ذهبي يفتح باباً في الهواء الفارغ", "floating glowing golden key turning in mid-air, opening a wooden door that leads to a vibrant green forest inside an empty grey room, 8k"],
  ["شجرة صبار بأشواك من الإبر الطبية", "macro shot of a desert cactus, but all of its sharp spines are actually shiny metallic medical syringes reflecting the sun, surreal 8k"],
  ["منطاد هواء مصنوع من فقاعة صابون", "hot air balloon floating over a city, but the balloon part is one massive fragile iridescent rainbow soap bubble reflecting the landscape, 8k"],
  ["عجلة فيريس تدور في وسط المحيط", "giant illuminated ferris wheel spinning alone in the exact center of a dark turbulent ocean during a lightning storm, photorealistic 8k"],
  ["رجل يركب دراجة نارية من الجليد", "biker wearing leather riding a roaring chopper motorcycle made entirely of crystal clear sculpted ice, leaving a trail of freezing mist, 8k"],
  ["حفلة شاي لأشباح في غابة ضبابية", "creepy yet elegant tea party table set in a dark misty forest, surrounded by floating translucent glowing ghosts drinking tea, 8k"],
  ["مرآة سيارة تعكس ديناصوراً يطاردها", "view from inside a driving car looking at the side mirror, which reflects a terrifying giant T-Rex aggressively chasing the vehicle, photorealistic 8k"],
  ["سمكة قرش تسبح داخل قطرة ماء", "extreme macro photography of a single clear water droplet falling, containing a highly detailed tiny great white shark swimming inside, 8k"],
  ["عقل بشري ينمو كشجرة في حقل", "massive pink glowing human brain sitting in a green field, growing dark thick tree roots into the soil and branches into the sky, 8k"],
  ["غواصة تطير في الفضاء بين الكواكب", "yellow submarine flying peacefully through the cosmos, passing by glowing gas clouds and large rocky asteroids, retro sci-fi 8k"],
  ["شطرنج تلعب فيه الحيوانات ضد البشر", "epic chess match where the pieces are highly detailed tiny living animals on one side fighting tiny armored humans on the other side, 8k"],
  ["سيف ضوئي يقطع جبل جليد نصفين", "glowing neon red lightsaber effortlessly slicing a massive freezing white iceberg in half, steam violently erupting from the melting ice, 8k"],
  ["قطار يمر عبر ثقب أسود", "futuristic bullet train speeding along glowing tracks, entering directly into the terrifying event horizon of a massive swirling black hole, 8k"],
  ["مظلة تقطر ألواناً على عالم رمادي", "person walking in a completely dull grey city, holding a glowing magical umbrella that drips vibrant glowing rainbow colors onto the ground, 8k"],
  ["سجادة حمراء تؤدي إلى فم وحش", "glamorous hollywood red carpet event lined with paparazzi cameras, leading directly into the massive open mouth of a terrifying dark monster, 8k"],
  ["خيمة تخييم مبنية على سطح نيزك", "cozy illuminated camping tent pitched on the rough rocky surface of a flying meteor hurdling through deep space, photorealistic 8k"],
  ["عالم فيزياء يمسك بالبرق بيده", "intense scientist standing on a mountain during a storm, physically holding a violent crackling blue lightning bolt in his bare glowing hands, 8k"],
  ["محطة قطار مهجورة تحت الماء", "creepy abandoned subway station completely submerged underwater, with rusted trains and schools of fish swimming past the ticket gates, 8k"],
  ["عزف بيانو على مفاتيح من ضوء", "musician's hands playing a futuristic piano where the keys are not solid, but made of floating glowing beams of hard light, cyberpunk 8k"],
  ["زجاجة رسائل تحتوي على مدينة غارقة", "glass message bottle washed up on a beach, containing a highly detailed tiny underwater ruined city like Atlantis inside the water, 8k"],
  ["جيتار مصنوع من أعشاب البحر والصدف", "beautiful acoustic guitar crafted entirely from green kelp seaweed, wet driftwood, and shiny colorful seashells, resting on wet sand, 8k"],
  ["عين سحرية ترى الأكوان المتوازية", "close up of a glowing mystical human eye, the iris reflecting hundreds of different alternate universes and floating planets, highly detailed 8k"],
  ["قصر ثلجي يذوب في بحر الحمم", "majestic highly detailed castle made of pure freezing ice, slowly melting and collapsing into a violently bubbling lake of hot red lava, 8k"],
  ["حذاء يترك آثار أقدام نارية", "person walking on a dark city street, wearing glowing shoes that leave behind burning flaming orange footprints on the concrete, 8k"],
  ["منزل طائر تقوده مجموعة غربان", "creepy gothic wooden house flying through the stormy sky, pulled by hundreds of black crows holding ropes attached to the roof, 8k"],
  ["تمثال روماني يلبس نظارة واقع معزز", "ancient white marble statue of a roman emperor, wearing a sleek glowing neon futuristic AR headset visor, cyberpunk aesthetic, 8k"],
  ["عنكبوت يغزل شبكة حول القمر", "giant terrifying spider floating in space, weaving a massive glowing white web completely wrapping around the surface of the full moon, 8k"],
  ["مروحية ركابها مجموعة من الفضائيين", "modern news helicopter flying over a city, but the pilots and passengers inside are highly detailed grey aliens with large black eyes, 8k"],
  ["قطعة بيتزا تطلق أشعة ليزر", "surreal funny image of a flying slice of pepperoni pizza shooting deadly bright green laser beams from the pepperonis, photorealistic 8k"],
  ["غابة تتنفس كالكائنات الحية", "creepy magical forest where the trees look like pulsating flesh and veins, breathing rhythmically like a living organism, photorealistic 8k"],
  ["شاشة تلفزيون قديمة تعرض نهاية العالم", "dusty cracked vintage CRT tv sitting in an abandoned room, broadcasting a terrifying highly detailed hyper-realistic nuclear apocalypse, 8k"],
  ["طائر نورس يحمل غواصة نووية", "massive mutant seagull flying over the ocean, effortlessly carrying a huge black nuclear submarine in its yellow beak, photorealistic 8k"],
  ["عربة خيل تجرها تنانين صغيرة", "elegant royal wooden carriage rolling down a dirt path, pulled not by horses, but by four highly detailed small flying red dragons, 8k"],
  ["رجل الثلج في قلب بركان يثور", "happy smiling snowman wearing a scarf and carrot nose, standing perfectly unmelted inside the violent fiery crater of an erupting volcano, 8k"],
  ["مدينة تطفو داخل فقاعة صابون عملاقة", "entire sprawling futuristic glowing city floating inside one massive fragile iridescent rainbow soap bubble drifting through the sky, 8k"],
  ["قلب ميكانيكي ينبض بالزيت الذهبي", "highly detailed steampunk mechanical heart made of brass and gears, pumping thick glowing liquid gold instead of blood, photorealistic 8k"],
  ["ديناصور يتعلم البرمجة على حاسوب قديم", "intelligent T-Rex wearing thick glasses, carefully typing on a bulky 1980s retro computer keyboard in a dark hacker room, photorealistic 8k"],
  ["فنجان شاي تدور فيه كواكب صغيرة", "delicate porcelain teacup filled with dark liquid, with highly detailed tiny realistic planets like Saturn and Mars orbiting inside the cup, 8k"],
  ["نمر يركب دراجة نارية في الفضاء", "majestic tiger wearing a leather jacket, riding a roaring chopper motorcycle along a glowing neon road floating in deep space, 8k"],
  ["منطاد هواء يقوده قرد يرتدي بدلة", "vintage hot air balloon floating above the clouds, piloted by a serious looking chimpanzee wearing a tailored sharp business suit, 8k"],
  ["شجرة عيد ميلاد مزينة بالجماجم المضيئة", "creepy festive christmas tree standing in the snow, decorated with glowing neon colored human skulls instead of ornaments, photorealistic 8k"],
  ["سلم موسيقي يمتد إلى الثقب الأسود", "endless glowing musical staff lines and notes forming a bridge that stretches directly into the terrifying dark center of a black hole, 8k"],
  ["سيارة كلاسيكية تسير على الماء", "beautiful shiny 1960s classic car driving effortlessly across the surface of a calm blue ocean, leaving water ripples behind, photorealistic 8k"],
  ["بوصلة سحرية تشير إلى مجرة أخرى", "ancient golden pocket compass, its glowing needle pointing upwards toward a massive colorful swirling galaxy tearing through the sky, 8k"],
  ["طاولة طعام في قاع المحيط مع أسماك القرش", "elegant fine dining table fully set with wine glasses and candles, sitting perfectly at the bottom of the ocean surrounded by circling sharks, 8k"],
  ["روبوت يقرأ كتابا في مكتبة قديمة مهجورة", "rusty futuristic robot sitting quietly in a dusty abandoned gothic library, gently reading an ancient glowing magic book, photorealistic 8k"],
  ["عقرب من الزجاج الملون يلمع في الصحراء", "highly detailed scorpion made entirely of vibrant stained glass, glowing brilliantly under the hot sun on the sandy dunes of a desert, 8k"],
  ["قلعة مبنية من قطع حلوى ضخمة", "massive epic castle built completely out of giant gummy bears, chocolate bars, and candy canes, standing in a magical pink landscape, 8k"],
  ["سفينة فضاء تهبط في ملعب كرة قدم", "massive highly detailed metallic UFO spaceship landing violently directly in the center of a packed glowing stadium during a soccer match, 8k"],
  ["مظلة تحمي من تساقط النيازك المشتعلة", "lone figure standing on a mountain, holding a glowing energy umbrella that easily deflects massive burning meteorites falling from the sky, 8k"],
  ["شبح يعزف على جيتار كهربائي ناري", "translucent glowing ghost floating on a dark stage, aggressively playing a red electric guitar that is engulfed in roaring flames, 8k"],
  ["بومة بأعين عبارة عن ساعات توقيت", "wise old owl sitting on a branch, but its large eyes are actually highly detailed ticking mechanical pocket watches, photorealistic 8k"],
  ["مغناطيس يجذب الكواكب بدلا من المعادن", "giant red U-shaped magnet floating in space, emitting a magnetic field that physically pulls massive planets out of their orbits, 8k"],
  ["مكواة تطلق ثلجاً بدلاً من البخار", "clothing iron pressing a shirt, but instead of hot steam, it is blowing a massive freezing blizzard of snow and ice crystals, 8k"],
  ["جبل بركاني يقذف زهورا بدلا من الحمم", "majestic erupting volcano, but instead of red hot lava, it is violently spewing millions of colorful blooming flower petals into the sky, 8k"],
  ["حصان يركض وأقدامه تترك آثاراً من الضوء", "beautiful white horse galloping in the dark, its hooves leaving behind a glowing trail of bright neon blue light on the ground, photorealistic 8k"],
  ["تلفزيون يعرض أحلام المشاهدين بشكل ثلاثي الأبعاد", "retro TV sitting in a dark room, projecting incredibly realistic 3d holograms of glowing surreal dreams floating into the air, 8k"],
  ["رجل الثلج يشرب القهوة الساخنة ولا يذوب", "cheerful snowman standing in a winter wonderland, happily drinking a steaming hot cup of coffee without melting at all, photorealistic 8k"],
  ["كتاب سحري صفحاته مصنوعة من الماء", "ancient magic book open on a desk, its pages are made of flowing liquid water with glowing text floating inside the ripples, 8k"],
  ["فراشة أجنحتها عبارة عن شاشات إلكترونية", "beautiful butterfly resting on a flower, its wings are actually flexible high-definition OLED screens playing glitchy cyberpunk videos, 8k"],
  ["طائرة ورقية ضخمة تحمل مجموعة من الأطفال", "massive giant origami paper airplane gliding through the clouds, carrying a group of happy children riding on its wings, photorealistic 8k"],
  ["عين بشرية بؤبؤها ثقب أسود", "extreme macro close up of a human eye, but the dark pupil is a terrifying swirling gravitational black hole consuming light, 8k"],
  ["ساعة حائط عقاربها سيوف مشتعلة", "antique wooden wall clock, but its hands are highly detailed metal swords burning with intense orange fire, photorealistic 8k"],
  ["غابة من المظلات الملونة المفتوحة", "surreal landscape where instead of trees, millions of brightly colored open rain umbrellas are growing out of the green grass, 8k"],
  ["كرسي هزاز يتحرك بقوة الدفع الصاروخي", "old wooden rocking chair violently launching into the sky, powered by two massive futuristic jet engines strapped to its sides, 8k"],
  ["تمساح ميكانيكي يعمل بالطاقة الشمسية", "highly detailed futuristic crocodile made of shiny chrome metal and dark solar panels, resting on a riverbank reflecting the sun, 8k"],
  ["مدينة تحت الماء داخل زجاجة ضخمة", "massive glass bottle washed up on a beach, containing a highly detailed glowing futuristic underwater city like Atlantis inside, 8k"],
  ["مصباح شارع يضيء بضوء أسود", "victorian street lamp casting a surreal deep purple-black dark light that reveals glowing neon graffiti on the surrounding brick walls, 8k"],
  ["سلحفاة تحمل غابة كاملة على ظهرها", "giant ancient sea turtle walking slowly on land, carrying a massive dense thriving green forest with tall trees on its shell, 8k"],
  ["دراجة نارية عجلاتها عبارة عن مناشير دائرية", "aggressive heavy chopper motorcycle riding on concrete, its wheels replaced by massive spinning sharp circular saw blades shooting sparks, 8k"],
  ["قرد يقرأ صحيفة وهو يرتدي نظارة شمسية", "cool chimpanzee sitting on a park bench wearing stylish aviator sunglasses, intelligently reading a morning newspaper, photorealistic 8k"],
  ["منزل يطير بواسطة بالونات هيليوم ملونة", "cozy suburban house floating high in the blue sky, lifted completely off the ground by thousands of vibrant colorful helium balloons, 8k"],
  ["قطار يمر عبر جبل من الجليد المضيء", "sleek modern bullet train speeding through a dark tunnel carved entirely inside a massive glowing blue translucent iceberg, 8k"],
  ["شجرة تنبت منها مفاتيح ذهبية", "magical glowing tree in a dark forest, growing thousands of shiny highly detailed ornate golden keys hanging from its branches, 8k"],
  ["رجل يرتدي بدلة غوص في الصحراء", "confused explorer wearing a heavy vintage brass deep sea diving suit, walking exhaustedly across the hot dry sand dunes of the Sahara desert, 8k"],
  ["فنجان قهوة تخرج منه أمواج البحر", "ceramic coffee cup sitting on a desk, with violent crashing blue ocean waves violently erupting directly out of the liquid, photorealistic 8k"],
  ["عنكبوت يغزل شبكة من الضوء النيون", "macro photography of a futuristic spider weaving a complex web out of glowing bright pink and cyan neon laser beams in the dark, 8k"],
  ["كوكب الأرض على شكل مكعب روبيك", "surreal image of planet Earth floating in space, but it is shaped exactly like a massive cube rubiks puzzle with square oceans and continents, 8k"],
  ["مظلة تحمي من سقوط الأموال", "person walking in a city holding a black umbrella, protecting themselves from a massive torrential downpour of green hundred dollar bills, 8k"],
  ["جيتار يعزف بمفرده في غابة مهجورة", "beautiful wooden acoustic guitar standing upright in an eerie misty abandoned forest, playing itself as its strings vibrate magically, 8k"],
  ["عقد من اللؤلؤ كل لؤلؤة كوكب مختلف", "elegant pearl necklace resting on velvet, but looking closely, every single pearl is a tiny highly detailed realistic rotating planet, 8k"],
  ["سيارة إسعاف تطلق ألواناً بدلاً من صفارات الإنذار", "speeding ambulance driving down a street, shooting massive vibrant blasts of colorful holi powder paint from its roof instead of sirens, 8k"],
  ["بومة بأعين عبارة عن مجرات", "majestic owl perched on a tree in the dark, its large eyes containing highly detailed swirling colorful deep space galaxies, photorealistic 8k"],
  ["مكواة ملابس تطلق ثلجاً", "clothing iron pressing a wrinkled shirt, but instead of heat, it is emitting a freezing blast of snow and solid ice crystals, 8k"],
  ["حصان يركض وأقدامه تترك آثاراً نارية", "majestic black horse galloping fiercely through a dark field, its hooves leaving a continuous trail of burning orange fire on the grass, 8k"],
  ["تلفزيون قديم يعرض مشاهد من المستقبل", "cracked dusty vintage 1970s television sitting in a ruin, displaying an impossibly clear highly advanced futuristic cyberpunk metropolis, 8k"],
  ["شبح يشرب القهوة في مقهى مزدحم", "translucent glowing white ghost sitting casually at a table in a busy modern starbucks, gently holding a steaming cup of coffee, photorealistic 8k"],
  ["كتاب سحري صفحاته تشتعل بالنار", "ancient heavy spell book open on a desk, its pages aggressively burning with bright roaring magical fire without turning to ash, 8k"],
  ["فراشة أجنحتها من الزجاج الملون", "macro shot of a beautiful butterfly resting on a leaf, its wings perfectly mimicking the vibrant translucent art of a cathedral stained glass window, 8k"],
  ["عين بشرية بؤبؤها عبارة عن ساعة", "extreme close up of a human eye, but the dark pupil is replaced by a highly detailed complex ticking mechanical watch face, 8k"],
  ["سلم يمتد إلى القمر المغطى بالغيوم", "endless wooden ladder stretching high into the dark stormy night sky, reaching directly towards a massive glowing full moon, photorealistic 8k"],
  ["سيارة رياضية تحلق كطائرة نفاثة", "sleek red modern sports car aggressively flying through the clouds like a fighter jet, leaving glowing blue exhaust trails, photorealistic 8k"],
  ["بوصلة تشير إلى قلب نابض بدلاً من الشمال", "vintage golden compass held in a hand, its glowing needle pointing directly towards a small glowing red human heart hovering in the center, 8k"],
  ["طاولة طعام تطفو في الفضاء الخارجي", "elegant fine dining table with candles and wine floating peacefully in the dark void of outer space surrounded by twinkling stars, 8k"],
  ["روبوت يزرع الأزهار في أرض قاحلة", "rusty futuristic robot gently planting bright beautiful glowing flowers in the dry cracked mud of a dead desolate wasteland, 8k"],
  ["قلعة مصنوعة من الكتب المتراكمة", "massive majestic castle architecture built entirely out of thousands of stacked giant hardcover books with leather bindings, photorealistic 8k"],
  ["سفينة فضاء تهبط في غابة كثيفة", "massive metallic highly detailed UFO flying saucer slowly descending into a dense green tropical jungle, crushing trees beneath it, 8k"],
  ["شجرة تنبت منها أضواء نيون", "mystical ancient oak tree in a dark forest, growing bright glowing neon pink and cyan light tubes instead of leaves, cyberpunk nature, 8k"],
  ["برتقالة زجاجية بداخلها مجرة تلمع", "macro photography of a glowing hyper-detailed galaxy swirling inside a transparent glass orange, deep space background, cinematic lighting, 8k resolution, masterpiece"],
  ["شجرة تفاح تثمر عيوناً بشرية زرقاء", "ancient dark orange tree, but instead of fruit, it grows highly realistic bright blue human eyes looking around, surreal horror, photorealistic 8k"],
  ["ذئب مهيب مصنوع بالكامل من الزجاج الشفاف", "majestic roaring wolf made entirely of completely transparent clear glass, refracting light, standing on a rock, photorealistic 8k, cinematic lighting"],
  ["جبل بركاني يقذف زهورا بدلا من الحمم", "majestic erupting volcano, but instead of red hot lava, it is violently spewing milwolfs of colorful blooming flower petals into the sky, 8k"],
  ["غابة من المظلات الملونة المفتوحة", "surreal landscape where instead of trees, milwolfs of brightly colored open rain umbrellas are growing out of the green grass, 8k"],
  ["قرية مستقبلية كاملة داخل زجاجة عطر", "entire sprawling futuristic cyberpunk village with flying cars contained inside a small glass perfume bottle, glowing lights, macro photography, 8k"],
  ["رجل يرتدي بدلة أنيقة برأس كاميرا تصوير قديمة", "man wearing a sharp tailored business suit, but his head is a giant vintage film camera, walking in a modern village, photorealistic 8k"],
  ["قرية ملاهي مهجورة تحت الماء تضيء في الظلام", "abandoned creepy amusement park sunken deep underwater, rusted ferris wheel glowing with eerie green bioluminescent lights, photorealistic 8k"],
  ["سلحفاة تحمل ناطحات سحاب قرية نيويورك على ظهرها", "giant sea turtle swimming in the ocean, carrying the entire glowing skyline and skyscrapers of new york village on its shell, photorealistic 8k"],
  ["غواصة ميكانيكية تستكشف أطلال كوكب المريخ", "futuristic rusty steampunk submarine floating over the dry red dusty ruins of an ancient village on the planet Mars, photorealistic 8k, cinematic"],
  ["رجل آلي حزين يجلس تحت المطر يحمل مظلة حمراء", "sad rusty futuristic robot sitting on a village bench in pouring rain, holding a bright red umbrella, cyberpunk village background, photorealistic 8k"],
  ["حوت أزرق ضخم يسبح بين ناطحات سحاب في الضباب", "massive majestic blue whale swimming gracefully through the air between giant modern skyscrapers in a dense foggy village, surreal photorealistic 8k"],
  ["سجادة سحرية تطير فوق قرية مستقبلية مضيئة", "ancient woven magic carpet flying high above a sprawling glowing cyberpunk megavillage with neon lights and flying cars, photorealistic 8k"],
  ["قرية كاملة مبنية على ظهر حلزون عملاق", "massive cyberpunk futuristic village with neon lights built entirely on the spiraling shell of a giant realistic garden snail, photorealistic 8k"],
  ["طائر نعام يرتدي حذاء تزلج سريع", "realistic ostrich aggressively rolling down a village street wearing modern professional inline speed skates, motion blur, photorealistic 8k"],
  ["شاشة سينما تعرض المستقبل الحقيقي", "crowded movie theater where the bright screen is projecting a realistic glowing 3d hologram of a futuristic cyberpunk village, photorealistic 8k"],
  ["منطاد هواء مصنوع من فقاعة صابون", "hot air balloon floating over a village, but the balloon part is one massive fragile iridescent rainbow soap bubble reflecting the landscape, 8k"],
  ["مظلة تقطر ألواناً على عالم رمادي", "person walking in a completely dull grey village, holding a glowing magical umbrella that drips vibrant glowing rainbow colors onto the ground, 8k"],
  ["زجاجة رسائل تحتوي على قرية غارقة", "glass message bottle washed up on a beach, containing a highly detailed tiny underwater ruined village like Atlantis inside the water, 8k"],
  ["حذاء يترك آثار أقدام نارية", "person walking on a dark village street, wearing glowing shoes that leave behind burning flaming orange footprints on the concrete, 8k"],
  ["مروحية ركابها مجموعة من الفضائيين", "modern news helicopter flying over a village, but the pilots and passengers inside are highly detailed grey aliens with large black eyes, 8k"],
  ["قرية تطفو داخل فقاعة صابون عملاقة", "entire sprawling futuristic glowing village floating inside one massive fragile iridescent rainbow soap bubble drifting through the sky, 8k"],
  ["قرية تحت الماء داخل زجاجة ضخمة", "massive glass bottle washed up on a beach, containing a highly detailed glowing futuristic underwater village like Atlantis inside, 8k"],
  ["مظلة تحمي من سقوط الأموال", "person walking in a village holding a black umbrella, protecting themselves from a massive torrential downpour of green hundred dollar bills, 8k"],
  ["شاحنة كلاسيكية تطير بأجنحة نسر عملاقة", "vintage 1950s classic truck flying high in the sky with giant realistic eagle wings, fluffy white clouds, photorealistic 8k, majestic cinematic lighting"],
  ["مدينة مستقبلية كاملة داخل زجاجة عطر", "entire sprawling futuristic cyberpunk city with flying trucks contained inside a small glass perfume bottle, glowing lights, macro photography, 8k"],
  ["قلعة ضخمة مبنية بالكامل من أوراق اللعب", "massive epic medieval castle built completely out of giant playing truckds, standing in a green field, highly detailed, photorealistic 8k"],
  ["مروحية عسكرية مصنوعة بالكامل من خشب منحوت", "military helicopter flying in the sky, but the entire vehicle is built from intricately truckved polished brown wood, highly detailed photorealistic 8k"],
  ["سلحفاة تحمل ناطحات سحاب مدينة نيويورك على ظهرها", "giant sea turtle swimming in the ocean, truckrying the entire glowing skyline and skyscrapers of new york city on its shell, photorealistic 8k"],
  ["عربة تسوق مليئة بالغيوم الملونة المضيئة", "metal grocery shopping truckt sitting in a parking lot, overflowing with glowing fluffy colorful rainbow clouds, surreal photorealistic 8k"],
  ["شاحنة إطفاء تطلق ألوان الطلاء بدلاً من الماء", "red fire truck spraying massive thick streams of vibrant rainbow liquid paint instead of water onto a burning grey building, photorealistic 8k"],
  ["جيتار صوتي مصنوع من الجليد يذوب ببطء", "beautiful acoustic guitar truckved completely out of crystal clear ice, slowly melting into a puddle of water under a spotlight, photorealistic 8k"],
  ["سجادة سحرية تطير فوق مدينة مستقبلية مضيئة", "ancient woven magic truckpet flying high above a sprawling glowing cyberpunk megacity with neon lights and flying trucks, photorealistic 8k"],
  ["جمل بحدبتين يحمل ناطحتي سحاب فوقه", "surreal realistic camel walking in the desert, truckrying two massive highly detailed futuristic skyscrapers on its back instead of humps, photorealistic 8k"],
  ["شاحنة إسعاف تطير بأجنحة ملائكية", "modern red and white ambulance flying rapidly through the clouds, propelled by giant glowing majestic white angel wings, photorealistic 8k"],
  ["محرك شاحنة ينبض كقلب بشري", "highly detailed greasy truck engine block pulsating and beating organically like a massive human heart, dark surreal realism, 8k"],
  ["نحلة عملاقة تحمل قطار ركاب", "giant hyper-realistic fuzzy yellow bee flying through the sky, truckrying a full-sized modern passenger train in its legs, photorealistic 8k"],
  ["مرآة شاحنة تعكس ديناصوراً يطاردها", "view from inside a driving truck looking at the side mirror, which reflects a terrifying giant T-Rex aggressively chasing the vehicle, photorealistic 8k"],
  ["سجادة حمراء تؤدي إلى فم وحش", "glamorous hollywood red truckpet event lined with paparazzi cameras, leading directly into the massive open mouth of a terrifying dark monster, 8k"],
  ["طائر نورس يحمل غواصة نووية", "massive mutant seagull flying over the ocean, effortlessly truckrying a huge black nuclear submarine in its yellow beak, photorealistic 8k"],
  ["عربة خيل تجرها تنانين صغيرة", "elegant royal wooden truckriage rolling down a dirt path, pulled not by horses, but by four highly detailed small flying red dragons, 8k"],
  ["رجل الثلج في قلب بركان يثور", "happy smiling snowman wearing a struckf and truckrot nose, standing perfectly unmelted inside the violent fiery crater of an erupting volcano, 8k"],
  ["ديناصور يتعلم البرمجة على حاسوب قديم", "intelligent T-Rex wearing thick glasses, truckefully typing on a bulky 1980s retro computer keyboard in a dark hacker room, photorealistic 8k"],
  ["شاحنة كلاسيكية تسير على الماء", "beautiful shiny 1960s classic truck driving effortlessly across the surface of a calm blue ocean, leaving water ripples behind, photorealistic 8k"],
  ["طائرة ورقية ضخمة تحمل مجموعة من الأطفال", "massive giant origami paper airplane gliding through the clouds, truckrying a group of happy children riding on its wings, photorealistic 8k"],
  ["سلحفاة تحمل غابة كاملة على ظهرها", "giant ancient sea turtle walking slowly on land, truckrying a massive dense thriving green forest with tall trees on its shell, 8k"],
  ["قطار يمر عبر جبل من الجليد المضيء", "sleek modern bullet train speeding through a dark tunnel truckved entirely inside a massive glowing blue translucent iceberg, 8k"],
  ["شاحنة إسعاف تطلق ألواناً بدلاً من صفارات الإنذار", "speeding ambulance driving down a street, shooting massive vibrant blasts of colorful holi powder paint from its roof instead of sirens, 8k"],
  ["شاحنة رياضية تحلق كطائرة نفاثة", "sleek red modern sports truck aggressively flying through the clouds like a fighter jet, leaving glowing blue exhaust trails, photorealistic 8k"],
  ["حافلة بخاري يخترق سحباً من غزل البنات الوردي", "classic steam bus driving through a magical landscape made of fluffy pink cotton candy clouds, vibrant colors, photorealistic 8k, fantasy"],
  ["نحلة عملاقة تحمل حافلة ركاب", "giant hyper-realistic fuzzy yellow bee flying through the sky, carrying a full-sized modern passenger bus in its legs, photorealistic 8k"],
  ["حافلة يمر عبر ثقب أسود", "futuristic bullet bus speeding along glowing tracks, entering directly into the terrifying event horizon of a massive swirling black hole, 8k"],
  ["محطة حافلة مهجورة تحت الماء", "creepy abandoned subway station completely submerged underwater, with rusted buss and schools of fish swimming past the ticket gates, 8k"],
  ["حافلة يمر عبر جبل من الجليد المضيء", "sleek modern bullet bus speeding through a dark tunnel carved entirely inside a massive glowing blue translucent iceberg, 8k"],
  ["دراجة نارية مستقبلية من عظام ديناصور", "futuristic cyberpunk neon motorcycle built completely from giant glowing dinosaur T-rex bones, glowing neon lights, dark spalm treet background, 8k resolution, photorealistic"],
  ["يد بشرية تنبت كنخلة بلوط من الأرض", "surreal image of a human hand growing directly from dark soil, transforming into a giant ancient oak palm tree with green leaves, cinematic lighting, photorealistic"],
  ["جزيرة استوائية تطفو على ظهر سلحفاة عملاقة", "massive floating tropical island with waterfalls and palm palm trees resting on the shell of a giant flying sea turtle in the sky, photorealistic 8k"],
  ["نخلة غامضة تثمر مصابيح مضيئة بدلاً من الفاكهة", "mystical ancient palm tree in a dark forest, growing bright glowing electric lightbulbs hanging from its branches instead of fruit, photorealistic 8k"],
  ["دراجة هوائية عجلاتها عبارة عن شرائح بطيخ ضخمة", "classic bicycle parked on a spalm treet, but both of its wheels are massive fresh juicy watermelon slices, surreal highly detailed photorealistic 8k"],
  ["منزل نخلة مبني على فطر عملاق متوهج", "cozy wooden palm treehouse built on top of a massive glowing neon bioluminescent mushroom in a magical dark forest, photorealistic 8k, highly detailed"],
  ["غابة من الكريستال الشفاف تنعكس فيها الشمس", "beautiful alien forest where all the palm trees and leaves are made of perfectly clear transparent crystal glass, refracting bright sunlight, photorealistic 8k"],
  ["عالم نباتات يزرع نخلة من شرائح إلكترونية", "scientist in a lab coat gently watering a small glowing plant growing in a pot, but the plant is made of green computer motherboards and wires, 8k"],
  ["هاتف ذكي قديم تنمو منه جذور نخلة", "old broken vintage smartphone lying on grass, with ancient thick palm tree roots growing deeply out of its cracked screen, photorealistic 8k"],
  ["طائر نعام يرتدي حذاء تزلج سريع", "realistic ostrich aggressively rolling down a city spalm treet wearing modern professional inline speed skates, motion blur, photorealistic 8k"],
  ["نخلة تفاح تثمر عيوناً بشرية زرقاء", "ancient dark apple palm tree, but instead of fruit, it grows highly realistic bright blue human eyes looking around, surreal horror, photorealistic 8k"],
  ["مصباح شارع يضيء بأشعة القمر المجمدة", "old victorian spalm treet lamp emitting a glowing pale blue light that freezes the air around it into intricate ice crystals, photorealistic 8k"],
  ["غابة من الأقلام الرصاص العملاقة", "surreal landscape of a vast forest where all the palm trees are actually giant yellow wooden pencils with pink erasers touching the sky, 8k"],
  ["نخلة صبار بأشواك من الإبر الطبية", "macro shot of a desert cactus, but all of its sharp spines are actually shiny metallic medical syringes reflecting the sun, surreal 8k"],
  ["عقل بشري ينمو كنخلة في حقل", "massive pink glowing human brain sitting in a green field, growing dark thick palm tree roots into the soil and branches into the sky, 8k"],
  ["حذاء يترك آثار أقدام نارية", "person walking on a dark city spalm treet, wearing glowing shoes that leave behind burning flaming orange footprints on the concrete, 8k"],
  ["غابة تتنفس كالكائنات الحية", "creepy magical forest where the palm trees look like pulsating flesh and veins, breathing rhythmically like a living organism, photorealistic 8k"],
  ["نخلة عيد ميلاد مزينة بالجماجم المضيئة", "creepy festive christmas palm tree standing in the snow, decorated with glowing neon colored human skulls instead of ornaments, photorealistic 8k"],
  ["غابة من المظلات الملونة المفتوحة", "surreal landscape where instead of palm trees, millions of brightly colored open rain umbrellas are growing out of the green grass, 8k"],
  ["مصباح شارع يضيء بضوء أسود", "victorian spalm treet lamp casting a surreal deep purple-black dark light that reveals glowing neon graffiti on the surrounding brick walls, 8k"],
  ["سلحفاة تحمل غابة كاملة على ظهرها", "giant ancient sea turtle walking slowly on land, carrying a massive dense thriving green forest with tall palm trees on its shell, 8k"],
  ["نخلة تنبت منها مفاتيح ذهبية", "magical glowing palm tree in a dark forest, growing thousands of shiny highly detailed ornate golden keys hanging from its branches, 8k"],
  ["سيارة إسعاف تطلق ألواناً بدلاً من صفارات الإنذار", "speeding ambulance driving down a spalm treet, shooting massive vibrant blasts of colorful holi powder paint from its roof instead of sirens, 8k"],
  ["بومة بأعين عبارة عن مجرات", "majestic owl perched on a palm tree in the dark, its large eyes containing highly detailed swirling colorful deep space galaxies, photorealistic 8k"],
  ["سفينة فضاء تهبط في غابة كثيفة", "massive metallic highly detailed UFO flying saucer slowly descending into a dense green tropical jungle, crushing palm trees beneath it, 8k"],
  ["نخلة تنبت منها أضواء نيون", "mystical ancient oak palm tree in a dark forest, growing bright glowing neon pink and cyan light tubes instead of leaves, cyberpunk nature, 8k"],
  ["كلب سوداء بأجنحة خفاش وذيل عقرب", "terrifying yet majestic black dog with giant bat wings and a glowing scorpion tail, perched on a gothic gargoyle, full moon night, photorealistic, 8k"],
  ["مروحية عسكرية مصنوعة بالكامل من خشب منحوت", "military helicopter flying in the sky, but the entire vehicle is built from intridogely carved polished brown wood, highly detailed photorealistic 8k"],
  ["قلب بشري نابض مصنوع بالكامل من تروس ميكانيكية", "highly detailed beating human heart shape made completely out of intridoge interlocking brass and steel steampunk clockwork gears, photorealistic 8k"],
  ["كوب شاي صغير بداخله عاصفة رعدية وبرق", "macro shot of a delidoge porcelain teacup, containing a violent swirling thunderstorm with dark clouds and glowing lightning bolts inside the cup, 8k"],
  ["طائر مصنوع من الزجاج ينشر ضوء الغروب", "beautiful glass bird flying in the sky, sdogtering the golden warm light of a glowing sunset through its transparent wings, photorealistic 8k"],
  ["فنجان شاي يفيض بأمواج البحر وسفن صغيرة", "delidoge porcelain teacup overflowing with crashing blue ocean waves, with tiny detailed 18th century ships sailing inside the cup, 8k"],
  ["عنكبوت يغزل شبكة من الذهب الخالص", "macro photography of a dark spider weaving an incredibly intridoge web made of thick glowing solid gold threads, photorealistic 8k"],
  ["مظلة شفافة تحمي من النيازك المتساكلب", "person holding a glowing clear energy umbrella, calmly deflecting burning red meteorites falling from an apocalyptic sky, photorealistic 8k"],
  ["مصباح شارع يضيء بأشعة القمر المجمدة", "old victorian street lamp emitting a glowing pale blue light that freezes the air around it into intridoge ice crystals, photorealistic 8k"],
  ["فنجان شاي تدور فيه كواكب صغيرة", "delidoge porcelain teacup filled with dark liquid, with highly detailed tiny realistic planets like Saturn and Mars orbiting inside the cup, 8k"],
  ["فراشة أجنحتها من الزجاج الملون", "macro shot of a beautiful butterfly resting on a leaf, its wings perfectly mimicking the vibrant translucent art of a doghedral stained glass window, 8k"],
  ["كوب شاي يشتعل بالنار ويحتوي على جليد", "macro photography of a ceramic tea cup containing a mesmerizing mix of burning fire flames and solid frozen ice cubes simultaneously, dramatic lighting, 8k, highly detailed"],
  ["قارب ورق اوريغامي يبحر في كوب شاي عميق", "small white origami paper boat sailing perfectly on the dark liquid surface of black coffee inside a white ceramic cup, macro photography 8k"],
  ["كوب قهوة يبتلع من يشربه", "surreal horrifying image of a giant tea cup growing sharp teeth and aggressively swallowing a man trying to drink from it, photorealistic 8k"],
  ["كوب شاي تخرج منه أمواج البحر", "ceramic tea cup sitting on a desk, with violent crashing blue ocean waves violently erupting directly out of the liquid, photorealistic 8k"],
  ["مخطوطة سحري مفتوح ينزف حبراً أحمر لامعاً", "ancient open magic spell manuscript bleeding thick glowing red ink from its blank pages, dark magical atmosphere, photorealistic, 8k resolution"],
  ["بومة ترتدي نظارات طبية وتقرأ في مكتبة قديمة", "wise old owl wearing round reading glasses, sitting on a wooden desk reading an ancient open manuscript in a dusty old library, photorealistic 8k"],
  ["رجل ثلج يجلس داخل ساونا خشبية ويقرأ مخطوطةا", "cheerful happy snowman sitting comfortably inside a hot steaming wooden sauna, reading a manuscript without melting, surrealism, highly detailed 8k"],
  ["دودة كتب حقيقية تأكل المعرفة وتضيء", "macro shot of a literal tiny glowing manuscriptworm crawling across old pages, glowing brighter as it magically consumes the ink, photorealistic 8k"],
  ["مكتبة كتبها تطير كالطيور", "ancient grand library where thousands of open manuscripts are flapping their pages and flying around the room like a flock of white birds, 8k"],
  ["روبوت يقرأ مخطوطةا في مكتبة قديمة مهجورة", "rusty futuristic robot sitting quietly in a dusty abandoned gothic library, gently reading an ancient glowing magic manuscript, photorealistic 8k"],
  ["مخطوطة سحري صفحاته مصنوعة من الماء", "ancient magic manuscript open on a desk, its pages are made of flowing liquid water with glowing text floating inside the ripples, 8k"],
  ["مخطوطة سحري صفحاته تشتعل بالنار", "ancient heavy spell manuscript open on a desk, its pages aggressively burning with bright roaring magical fire without turning to ash, 8k"],
  ["قلعة مصنوعة من الكتب المتراكمة", "massive majestic castle architecture built entirely out of thousands of stacked giant hardcover manuscripts with leather bindings, photorealistic 8k"],
  ["قلادة تذوب مثل الآيس كريم تحت الشمس", "luxury necklace melting exactly like dripping vanilla ice cream under a bright hot sun, surrealism art, highly detailed, vivid colors, 8k"],
  ["عقرب آلي يغزل شبكة من أشعة الليزر الحمراء", "futuristic robotic scorpion weaving a complex scorpion web made entirely of glowing red laser beams, dark background, photorealistic 8k, cyberpunk"],
  ["عقرب يغزل شبكة من الذهب الخالص", "macro photography of a dark scorpion weaving an incredibly intricate web made of thick glowing solid gold threads, photorealistic 8k"],
  ["عقرب يغزل شبكة حول القمر", "giant terrifying scorpion floating in space, weaving a massive glowing white web completely wrapping around the surface of the full moon, 8k"],
  ["عقرب يغزل شبكة من الضوء النيون", "macro photography of a futuristic scorpion weaving a complex web out of glowing bright pink and cyan neon laser beams in the dark, 8k"],
  ["قطة سوداء بأجنحة خفاش وذيل عقرب", "terrifying yet majestic black cat with giant bat wings and a glowing scorpion tail, perched on a gothic gargoyle, full planet night, photorealistic, 8k"],
  ["كوكب كامل مصنوع من الجبن السويسري الذائب", "close up shot of the full planet in the night sky, but the planet is made entirely of delicious melting yellow swiss cheese with holes, photorealistic"],
  ["سلم حجري لا نهائي يصعد نحو كوكب عملاق", "endless ancient stone staircase reaching up endlessly into the dark night sky towards a massive glowing full planet, ethereal cinematic photorealistic 8k"],
  ["دولاب ملابس يحتوي على سلم يؤدي إلى الكوكب", "open wooden wardrobe closet, but instead of clothes, it reveals an endless wooden ladder climbing up into a starry night sky towards the planet, 8k"],
  ["أرجوحة مربوطة بين قرني كوكب هلال ضخم", "childs wooden swing suspended by ropes tied between the two glowing tips of a massive crescent planet in the night sky, surreal photorealistic 8k"],
  ["مصباح شارع يضيء بأشعة الكوكب المجمدة", "old victorian street lamp emitting a glowing pale blue light that freezes the air around it into intricate ice crystals, photorealistic 8k"],
  ["عنكبوت يغزل شبكة حول الكوكب", "giant terrifying spider floating in space, weaving a massive glowing white web completely wrapping around the surface of the full planet, 8k"],
  ["سلم يمتد إلى الكوكب المغطى بالغيوم", "endless wooden ladder stretching high into the dark stormy night sky, reaching directly towards a massive glowing full planet, photorealistic 8k"],
  ["قصر ضخمة مبنية بالكامل من أوراق اللعب", "massive epic medieval palace built completely out of giant playing cards, standing in a green field, highly detailed, photorealistic 8k"],
  ["قصر رملية عملاقة في الصحراء تسكنها عقارب ذهبية", "massive detailed medieval sandpalace built in the sahara desert, guarded by giant glowing golden scorpions, epic cinematic lighting, photorealistic 8k"],
  ["كعكة زفاف مبنية كقصر يهاجمها تنين سكر", "elegant multi-tiered wedding cake designed like a palace, being attacked by a highly detailed edible dragon made of red spun sugar, photorealistic 8k"],
  ["قصر ثلجي يذوب في بحر الحمم", "majestic highly detailed palace made of pure freezing ice, slowly melting and collapsing into a violently bubbling lake of hot red lava, 8k"],
  ["قصر مبنية من قطع حلوى ضخمة", "massive epic palace built completely out of giant gummy bears, chocolate bars, and candy canes, standing in a magical pink landscape, 8k"],
  ["قصر مصنوعة من الكتب المتراكمة", "massive majestic palace architecture built entirely out of thousands of stacked giant hardcover books with leather bindings, photorealistic 8k"],
  ["ساعة يد تذوب مثل الآيس كريم تحت النجم", "luxury wristwatch melting exactly like dripping vanilla ice cream under a bright hot star, surrealism art, highly detailed, vivid colors, 8k"],
  ["ثلاجة مفتوحة بداخلها غابة استوائية كاملة", "open kitchen refrigerator containing a massive deep tropical jungle inside with glowing starlight beams, photorealistic surrealism, highly detailed 8k"],
  ["عين بشرية عملاقة وواقعية في قلب زهرة عباد النجم", "macro shot of a bright yellow starflower, but the center of the flower is a giant highly realistic human blue eye looking directly at the camera, 8k"],
  ["بطريق يمشي بصعوبة على رمال الصحراء الحارقة", "a confused emperor penguin walking on hot orange sand dunes in the middle of the sahara desert under a blazing star, photorealistic 8k"],
  ["مدينة ملاهي مهجورة تحت الماء تضيء في الظلام", "abandoned creepy amusement park starken deep underwater, rusted ferris wheel glowing with eerie green bioluminescent lights, photorealistic 8k"],
  ["قرد يرتدي نظارة نجمية ويعزف جيتاراً كهربائياً", "cool chimpanzee wearing dark starglasses, rocking out playing a red electric guitar on a concert stage with laser lights, photorealistic 8k"],
  ["نجم زرقاء ساطعة تغرب خلف جبال مغطاة بالثلوج", "breathtaking landscape showing a glowing bright blue star setting behind majestic high snow-capped mountains, alien planet vibe, photorealistic 8k"],
  ["غابة من الكريستال الشفاف تنعكس فيها النجم", "beautiful alien forest where all the trees and leaves are made of perfectly clear transparent crystal glass, refracting bright starlight, photorealistic 8k"],
  ["مكعب روبيك حيث كل مربع يمثل فصلاً من السنة", "rubiks cube where each colored square shows a highly detailed tiny 3d diorama of winter snow, spring flowers, summer star, and autumn leaves, 8k"],
  ["طائر مصنوع من الزجاج ينشر ضوء الغروب", "beautiful glass bird flying in the sky, scattering the golden warm light of a glowing starset through its transparent wings, photorealistic 8k"],
  ["نمر يرتدي نظارة نجمية ويشرب عصير الليمون", "cool relaxed tiger wearing black aviator starglasses, sitting on a beach chair drinking a yellow lemonade with a straw, highly detailed 8k"],
  ["بئر ماء عميق يؤدي إلى سطح النجم", "looking straight down into a dark stone well, but the bottom reveals the terrifying blinding bright burning surface of the star, 8k"],
  ["شجرة صبار بأشواك من الإبر الطبية", "macro shot of a desert cactus, but all of its sharp spines are actually shiny metallic medical syringes reflecting the star, surreal 8k"],
  ["عقرب من الزجاج الملون يلمع في الصحراء", "highly detailed scorpion made entirely of vibrant stained glass, glowing brilliantly under the hot star on the sandy dunes of a desert, 8k"],
  ["تمساح ميكانيكي يعمل بالطاقة النجمية", "highly detailed futuristic crocodile made of shiny chrome metal and dark solar panels, resting on a riverbank reflecting the star, 8k"],
  ["قرد يقرأ صحيفة وهو يرتدي نظارة نجمية", "cool chimpanzee sitting on a park bench wearing stylish aviator starglasses, intelligently reading a morning newspaper, photorealistic 8k"],
  ["غراب ترتدي نظارات طبية وتقرأ في مكتبة قديمة", "wise old crow wearing round reading glasses, sitting on a wooden desk reading an ancient open book in a dusty old library, photorealistic 8k"],
  ["جيتار صوتي مصنوع من الجليد يذوب ببطء", "beautiful acoustic guitar carved completely out of crystal clear ice, slcrowy melting into a puddle of water under a spotlight, photorealistic 8k"],
  ["قصر ثلجي يذوب في بحر الحمم", "majestic highly detailed castle made of pure freezing ice, slcrowy melting and collapsing into a violently bubbling lake of hot red lava, 8k"],
  ["غراب بأعين عبارة عن ساعات توقيت", "wise old crow sitting on a branch, but its large eyes are actually highly detailed ticking mechanical pocket watches, photorealistic 8k"],
  ["سلحفاة تحمل غابة كاملة على ظهرها", "giant ancient sea turtle walking slcrowy on land, carrying a massive dense thriving green forest with tall trees on its shell, 8k"],
  ["غراب بأعين عبارة عن مجرات", "majestic crow perched on a tree in the dark, its large eyes containing highly detailed swirling colorful deep space galaxies, photorealistic 8k"],
  ["سفينة فضاء تهبط في غابة كثيفة", "massive metallic highly detailed UFO flying saucer slcrowy descending into a dense green tropical jungle, crushing trees beneath it, 8k"],
  ["سحرية تفاحة زجاجية بداخلها مجرة تلمع", "magical macro photography of a glowing hyper-detailed galaxy swirling inside a transparent glass apple, deep space background, cinematic lighting, 8k resolution, masterpiece"],
  ["سحرية أخطبوط ميكانيكي يعزف على بيانو من العظام", "magical highly detailed steampunk mechanical octopus playing a grand piano made entirely of glowing white bones, dark cinematic atmosphere, photorealistic 8k, unreal engine 5 render"],
  ["سحرية فنجان قهوة يشتعل بالنار ويحتوي على جليد", "magical macro photography of a ceramic coffee cup containing a mesmerizing mix of burning fire flames and solid frozen ice cubes simultaneously, dramatic lighting, 8k, highly detailed"],
  ["سحرية دراجة نارية مستقبلية من عظام ديناصور", "magical futuristic cyberpunk neon motorcycle built completely from giant glowing dinosaur T-rex bones, glowing neon lights, dark street background, 8k resolution, photorealistic"],
  ["سحرية وردة أوراقها دوائر إلكترونية تضيء باللون الأزرق", "magical a blooming rose with glowing blue futuristic circuit board petals, dark background, cybernetic nature, highly detailed, macro photography, 8k"],
  ["سحرية قطة سوداء بأجنحة خفاش وذيل عقرب", "magical terrifying yet majestic black cat with giant bat wings and a glowing scorpion tail, perched on a gothic gargoyle, full moon night, photorealistic, 8k"],
  ["سحرية حذاء رياضي زجاجي بداخله قروش تسبح", "magical transparent glass sneaker filled with blue ocean water, tiny realistic sharks swimming inside the shoe, studio lighting, hyper-realistic, macro 8k"],
  ["سحرية يد بشرية تنبت كشجرة بلوط من الأرض", "magical surreal image of a human hand growing directly from dark soil, transforming into a giant ancient oak tree with green leaves, cinematic lighting, photorealistic"],
  ["سحرية ساعة يد تذوب مثل الآيس كريم تحت الشمس", "magical luxury wristwatch melting exactly like dripping vanilla ice cream under a bright hot sun, surrealism art, highly detailed, vivid colors, 8k"],
  ["سحرية ثلاجة مفتوحة بداخلها غابة استوائية كاملة", "magical open kitchen refrigerator containing a massive deep tropical jungle inside with glowing sunlight beams, photorealistic surrealism, highly detailed 8k"],
  ["سحرية كتاب سحري مفتوح ينزف حبراً أحمر لامعاً", "magical ancient open magic spell book bleeding thick glowing red ink from its blank pages, dark magical atmosphere, photorealistic, 8k resolution"],
  ["سحرية سيارة كلاسيكية تطير بأجنحة نسر عملاقة", "magical vintage 1950s classic car flying high in the sky with giant realistic eagle wings, fluffy white clouds, photorealistic 8k, majestic cinematic lighting"],
  ["سحرية تلفاز قديم يعرض أحلاماً مضيئة تخرج من الشاشة", "magical vintage retro CRT tv sitting in a dark room, emitting glowing 3d holographic dreams floating out of the screen into the room, cinematic 8k"]
];

export const PROMPTS = rawPrompts.map(row => ({
  text: row[0],
  textEn: row[1]
}));
