/**
 * Maps each Arabic card label to its English Wikipedia article title.
 * Used to fetch real photo thumbnails via the Wikipedia REST API.
 */
export const CARD_WIKI_TITLES: Record<string, string> = {
  // ── Animals ──────────────────────────────────────────────────────────────
  'أسد':      'Lion',
  'نمر':      'Tiger',
  'فيل':      'African_bush_elephant',
  'زرافة':    'Giraffe',
  'حصان':     'Horse',
  'ديك':      'Rooster',
  'قط':       'Cat',
  'كلب':      'Dog',
  'أرنب':     'Rabbit',
  'ضفدع':     'Frog',
  'بومة':     'Owl',
  'دلفين':    'Dolphin',
  'تمساح':    'Nile_crocodile',
  'ثعبان':    'Snake',
  'طاووس':    'Indian_peafowl',
  'فراشة':    'Butterfly',
  'دب':       'Brown_bear',
  'ذئب':      'Wolf',
  'قرد':      'Chimpanzee',
  'حمار':     'Donkey',
  'جمل':      'Dromedary',
  'بقرة':     'Cattle',
  'خروف':     'Sheep',
  'دجاجة':    'Chicken',

  // ── Football Stars ────────────────────────────────────────────────────────
  'رونالدو':   'Cristiano_Ronaldo',
  'ميسي':      'Lionel_Messi',
  'نيمار':     'Neymar',
  'مبابي':     'Kylian_Mbappé',
  'هالاند':    'Erling_Haaland',
  'بنزيمة':    'Karim_Benzema',
  'لوكاكو':    'Romelu_Lukaku',
  'ساكا':      'Bukayo_Saka',
  'فينيسيوس':  'Vinícius_Júnior',
  'ديبالا':    'Paulo_Dybala',
  'كيليان':    'Kylian_Mbappé',
  'سالاح':     'Mohamed_Salah',
  'فيرمينو':   'Roberto_Firmino',
  'ماني':      'Sadio_Mané',
  'موراتا':    'Álvaro_Morata',
  'غريزمان':   'Antoine_Griezmann',
  'كانسيلو':   'João_Cancelo',
  'برونو':     'Bruno_Fernandes',
  'ثياغو':     'Thiago_Alcântara',
  'لوكاس':     'Lucas_Paquetá',
  'لامين':     'Lamine_Yamal',
  'بيدري':     'Pedri',
  'غافي':      'Gavi_(footballer)',
  'بيلينغهام': 'Jude_Bellingham',

  // ── Egyptian Celebrities ──────────────────────────────────────────────────
  'محمد صلاح':     'Mohamed_Salah',
  'عمرو دياب':     'Amr_Diab',
  'أم كلثوم':      'Umm_Kulthum',
  'نجيب محفوظ':    'Naguib_Mahfouz',
  'أحمد زكي':      'Ahmed_Zaki_(actor)',
  'ليلى علوي':     'Laila_Elwi',
  'يسرا':          'Yousra_(actress)',
  'عادل إمام':     'Adel_Imam',
  'محمود ياسين':   'Mahmoud_Yassin',
  'فاتن حمامة':    'Faten_Hamama',
  'رشدي أباظة':    'Rushdy_Abaza',
  'سعاد حسني':     'Soad_Hosny',
  'هاني شاكر':     'Hany_Shaker',
  'علاء مبارك':    'Alaa_Mubarak',
  'بشير الديك':    'Bashir_El_Dik',
  'مصطفى فهمي':   'Mostafa_Fahmy_(actor)',
  'نبيلة عبيد':    'Nabila_Obeid',
  'سمير غانم':     'Samir_Ghanem',
  'فريد شوقي':     'Farid_Shawqi',
  'شريف عرفة':     'Sherif_Arafa',
  'مني زكي':       'Mona_Zaki',
  'أحمد السقا':    'Ahmed_El-Sakka',
  'هند صبري':      'Hend_Sabry',
  'كريم عبد العزيز': 'Karim_Abdel_Aziz',

  // ── Food ─────────────────────────────────────────────────────────────────
  'كشري':      'Kushari',
  'فول':       'Ful_medames',
  'طعمية':     'Falafel',
  'كباب':      'Kebab',
  'مشوي':      'Grilling',
  'كنافة':     'Kunafeh',
  'بقلاوة':    'Baklava',
  'أم علي':    'Om_Ali',
  'ملوخية':    'Mulukhiyah',
  'مكرونة':    'Pasta',
  'بيتزا':     'Pizza',
  'برجر':      'Hamburger',
  'سوشي':      'Sushi',
  'شاورما':    'Shawarma',
  'فلافل':     'Falafel',
  'حمص':       'Hummus',
  'تبولة':     'Tabbouleh',
  'منسف':      'Mansaf',
  'كفتة':      'Kofta',
  'سمك':       'Fish',
  'جمبري':     'Shrimp',
  'بطاطس':     'Potato',
  'سلطة':      'Salad',
  'آيس كريم':  'Ice_cream',

  // ── People (professions) ─────────────────────────────────────────────────
  'طبيب':      'Physician',
  'مدرس':      'Teacher',
  'طيار':      'Aviator',
  'شيف':       'Chef',
  'مهندس':     'Engineer',
  'محامي':     'Lawyer',
  'رسام':      'Illustrator',
  'موسيقار':   'Musician',
  'رياضي':     'Athlete',
  'صياد':      'Fisherman',
  'فلاح':      'Farmer',
  'بناء':      'Construction_worker',
  'ممرضة':     'Nursing',
  'شرطي':      'Police_officer',
  'مطفئ':      'Firefighter',
  'صحفي':      'Journalist',
  'عالم':      'Scientist',
  'نجار':      'Carpenter',
  'خياط':      'Tailor',
  'حلاق':      'Barber',
  'ساحر':      'Magician_(illusionist)',
  'باعة':      'Market_trader',
  'قاضي':      'Judge',
  'دبلوماسي':  'Diplomat',
};
