/**
 * Maps each Arabic card label to its English Wikipedia article title.
 * Used to fetch real photo thumbnails via the Wikipedia REST API.
 */
export const CARD_WIKI_TITLES: Record<string, string> = {
  // ── Animals — solo, clear-face article picks ──────────────────────────────
  'أسد': 'Lion',
  'نمر': 'Bengal_tiger',
  'فيل': 'African_bush_elephant',
  'زرافة': 'Giraffe',
  'حصان': 'horse',
  'ديك': 'Red_junglefowl',
  'قط': 'Tabby_cat',
  'كلب': 'Dog',
  'أرنب': 'Rabbit',
  'ضفدع': 'Frog',
  'بومة': 'Great_horned_owl',
  'دلفين': 'Dolphin',
  'تمساح': 'American_alligator',
  'ثعبان': 'Ball_python',
  'طاووس': 'Indian_peafowl',
  'فراشة': 'Monarch_butterfly',
  'دب': 'Brown_bear',
  'ذئب': 'Gray_wolf',
  'قرد': 'Chimpanzee',
  'حمار': 'North_American_donkeys',
  'جمل': 'Dromedary',
  'بقرة': 'Cattle',
  'خروف': 'Merino_sheep',
  'دجاجة': 'Plymouth_Rock_chicken',

  // ── Football Stars ────────────────────────────────────────────────────────
  'رونالدو': 'Cristiano_Ronaldo',
  'ميسي': 'Lionel_Messi',
  'نيمار': 'Neymar',
  'مبابي': 'Kylian_Mbappé',
  'هالاند': 'Erling_Haaland',
  'بنزيمة': 'Karim_Benzema',
  'لوكاكو': 'Romelu_Lukaku',
  'ساكا': 'Bukayo_Saka',
  'فينيسيوس': 'Vinícius_Júnior',
  'ديبالا': 'Paulo_Dybala',
  'زيدان': 'Zinedine_Zidane',
  'محمد صلاح': 'Mohamed_Salah',
  'فيرمينو': 'Roberto_Firmino',
  'ماني': 'Sadio_Mané',
  'موراتا': 'Álvaro_Morata',
  'غريزمان': 'Antoine_Griezmann',
  'كانسيلو': 'João_Cancelo',
  'برونو': 'Bruno_Fernandes',
  'ثياغو': 'Thiago_Alcântara',
  'لامين': 'Lamine_Yamal',
  'بيدري': 'Pedri',
  'غافي': 'Gavi_(footballer)',
  'بيلينغهام': 'Jude_Bellingham',
  'محمد أبو تريكه': 'Mohamed_Aboutrika',

  // ── Egyptian Celebrities ──────────────────────────────────────────────────
  'عمرو دياب': 'Amr_Diab',
  'أم كلثوم': 'Umm_Kulthum',
  'نجيب محفوظ': 'Naguib_Mahfouz',
  'عادل إمام': 'Adel_Imam',
  'رشدي أباظة': 'Rushdy_Abaza',
  'سعاد حسني': 'Soad_Hosny',
  'طه حسين': 'Taha_Hussein',
  'محمد منير': 'Mohamed_Mounir',
  'سمير غانم': 'Samir_Ghanem',
  'إسماعيل يس': 'Ismail_Yassin',
  'منى زكي': 'Mona_Zaki',
  'أحمد السقا': 'Ahmed_El-Sakka',
  'هند صبري': 'Hend_Sabry',
  'كريم عبد العزيز': 'Karim_Abdel_Aziz',
  'منى الشاذلي': 'Mona_El-Shazly',
  'إلهام شاهين': 'Elham_Shahin',
  'أحمد حلمي': 'Ahmed_Helmy',
  'محمد هنيدي': 'Mohamed_Henedi',
  'أحمد عز': 'Ahmed_Ezz_(actor)',
  'منة شلبي': 'Menna_Shalabi',
  'مي عز الدين': 'Mai_Ezz_Eldin',
  'محمد رمضان': 'Mohamed_Ramadan_(actor)',
  'تامر حسني': 'Tamer_Hosny',
  'مصطفى شعبان': 'Mostafa_Shaban',
  'رامز جلال': 'Ramez_Galal',
  'دنيا سمير غانم': 'Donia_Samir_Ghanem',
  'يسرا': 'Yousra',
  'نور الشريف': 'Nour_El-Sherif',
  'حسين فهمي': 'Hussein_Fahmy',
  'مصطفى قمر': 'Mostafa_Amar',
  'شيرين عبد الوهاب': 'Sherine',


  // ── Food ─────────────────────────────────────────────────────────────────
  'كشري': 'Kushari',
  'فول': 'Ful_medames',
  'لحمة مشوية': 'Mixed_grill',           // clear grilled meat image
  'كباب': 'Kebab',
  'فتة': 'Fatta',                  // Egyptian dish
  'كنافة': 'Kunafeh',
  'أم علي': 'Om_Ali',
  'ملوخية': 'Mulukhiyah',
  'مكرونة': 'Pasta',
  'بيتزا': 'Pizza',
  'برجر': 'Hamburger',
  'سوشي': 'Sushi',
  'شاورما': 'Shawarma',
  'فلافل': 'Falafel',
  'محشي': 'Mahshi',                // Egyptian stuffed veg
  'حواوشي': 'Hawawshi',             // Egyptian minced meat pastry
  'مسقعة': 'Moussaka',
  'كفتة': 'Kofta',
  'سمك': 'Fish',
  'جمبري': 'Shrimp',
  'بطاطس مقلية': 'French_fries',          // fried, not raw potatoes
  'سلطة': 'Salad',
  'آيس كريم': 'Ice_cream',
  'بقلاوة': 'Baklava',

  // ── People (professions) ─────────────────────────────────────────────────
  'طبيب': 'Physician',
  'مدرس': 'Teacher',
  'طيار': 'Aviator',
  'شيف': 'Chef',
  'مهندس': 'Engineer',
  'محامي': 'Lawyer',
  'رسام': 'Illustrator',
  'موسيقار': 'Musician',
  'رياضي': 'Athlete',
  'صياد': 'Fisherman',
  'فلاح': 'Farmer',
  'بناء': 'Construction_worker',
  'ممرضة': 'Nursing',
  'شرطي': 'Police_officer',
  'مطفئ': 'Firefighter',
  'صحفي': 'Journalist',
  'عالم': 'Scientist',
  'نجار': 'Carpenter',
  'خياط': 'Tailor',
  'حلاق': 'Barber',
  'ساحر': 'Magician_(illusionist)',
  'باعة': 'Market_trader',
  'قاضي': 'Judge',
  'دبلوماسي': 'Diplomat',
};
