const PROMPTS = [
  { ar: "تفاحة بداخلها مجرة", en: "apple containing glowing galaxy inside, photorealistic" },
  { ar: "أخطبوط يعزف بيانو من عظام", en: "octopus playing piano made of bones, surreal photorealistic" },
  { ar: "نار ومياه متجمدة في كوب", en: "coffee cup with fire and ice water simultaneously, macro photography" },
  { ar: "دراجة نارية بهيكل ديناصور", en: "futuristic neon motorcycle built from dinosaur bones" },
  { ar: "وردة أوراقها إلكترونية تضيء", en: "rose with glowing circuit board petals" },
  { ar: "قطة بجناح خفاش وعقرب", en: "cat with bat wings and scorpion tail" },
  { ar: "حذاء زجاجي بداخله قروش", en: "glass sneaker filled with ocean water and sharks" },
  { ar: "يد بشرية تنبت كشجرة", en: "human hand growing from soil as a tree" },
  { ar: "ساعة تذوب كآيس كريم", en: "wristwatch melting like ice cream under sun, surreal" },
  { ar: "ثلاجة بداخلها غابة", en: "refrigerator containing full tropical jungle inside" },
  { ar: "كتاب ينزف حبراً أحمر", en: "open book bleeding thick red ink" },
  { ar: "سيارة تطير بأجنحة نسر", en: "car flying with giant eagle wings in sky" },
  { ar: "تلفاز يعرض أحلامك", en: "vintage tv showing glowing dreams coming out of screen" },
  { ar: "فيل بحجم نملة", en: "tiny elephant the size of an ant on a coin" },
  { ar: "مدينة داخل زجاجة", en: "entire futuristic city inside a glass bottle" },
  { ar: "بيتزا عائمة في الفضاء", en: "pizza slice floating in outer space near stars" },
  { ar: "أسد من زجاج شفاف", en: "lion made entirely of transparent clear glass" },
  { ar: "نهر من الذهب السائل", en: "river flowing with glowing liquid gold" },
  { ar: "عنكبوت يغزل شبكة من ليزر", en: "spider weaving web made of red laser beams" },
  { ar: "جزيرة طائرة على سلحفاة", en: "floating island on the back of a giant turtle" },
  { ar: "قمر مصنوع من الجبن", en: "moon made of melted swiss cheese, high detail" },
  { ar: "قلعة تبنى من أوراق اللعب", en: "giant castle built completely out of playing cards" },
  { ar: "سحابة تمطر أموال", en: "dark cloud raining golden coins and money bills" },
  { ar: "جبل بركاني يقذف جليد", en: "volcano erupting snow and ice cubes instead of lava" },
  { ar: "سمكة قرش تطير ببالونات", en: "shark floating in air tied to colorful balloons" },
  { ar: "هاتف يخرج منه وحش", en: "smartphone screen with 3d monster claw reaching out" },
  { ar: "رجل برأس كاميرا قديمة", en: "man wearing suit with vintage camera instead of head" },
  { ar: "شجرة تثمر لمبات مضيئة", en: "tree growing glowing lightbulbs instead of fruit" },
  { ar: "مظلة تعكس الفضاء الخارجي", en: "umbrella protecting from rain but showing galaxy underneath" },
  { ar: "قطار يمر وسط سحب وردية", en: "steam train driving through pink cotton candy clouds" },
  { ar: "عين بشرية داخل زهرة", en: "giant realistic human eye in the center of a sunflower" },
  { ar: "بيانو يخرج منه دخان ملون", en: "grand piano emitting thick colorful smoke when played" },
  { ar: "دراجة بعجلات من بطيخ", en: "bicycle with giant watermelons as wheels" },
  { ar: "فراشة بجناحي من نار", en: "butterfly with wings made of glowing fire" },
  { ar: "تمثال حرية يرتدي سماعات", en: "statue of liberty wearing giant modern headphones" },
  { ar: "بومة تقرأ كتاب في مكتبة", en: "owl wearing glasses reading a book in old library" },
  { ar: "بطريق في الصحراء الكبرى", en: "penguin walking on hot sand dunes in sahara desert" },
  { ar: "طائرة هليكوبتر من خشب", en: "helicopter built entirely from carved wood" },
  { ar: "سلالم تصعد إلى القمر", en: "endless staircase reaching up to the full moon" },
  { ar: "نحلة ميكانيكية دقيقة", en: "highly detailed mechanical steampunk bee" },
  { ar: "قارب ورقي يبحر في فنجان", en: "origami paper boat sailing in a coffee cup" },
  { ar: "مدينة ملاهي تحت الماء", en: "abandoned amusement park underwater with glowing lights" },
  { ar: "كرسي يطير بصواريخ", en: "wooden chair flying with jet rockets attached" },
  { ar: "قرد يعزف جيتار كهربائي", en: "monkey rocking out on electric guitar on stage" },
  { ar: "باب خشبي في وسط المحيط", en: "freestanding wooden door opening in middle of ocean" },
  { ar: "عين عاصفة بداخلها مجرة", en: "eye of tornado revealing outer space galaxy inside" },
  { ar: "سفينة فضائية تهبط في غابة", en: "ufo spaceship landing in deep green forest" },
  { ar: "وحش بحري من بلاستيك", en: "sea monster made of recycled plastic bottles" },
  { ar: "شمس زرقاء فوق جبال", en: "bright blue sun setting over snow mountains" },
  { ar: "قلب نابض من تروس", en: "beating human heart made of clockwork gears" }
];

const WORDS = [
  { word: "كرة القدم", forbiddenWords: ["ملعب", "هدف", "حكم", "فريق", "لاعب", "مباراة", "رياضة", "شوط", "كأس", "جمهور"] },
  { word: "مدرسة", forbiddenWords: ["فصل", "طالب", "معلم", "سبورة", "درس", "كتاب", "امتحان", "واجب", "حصص", "مدير"] },
  { word: "بحر", forbiddenWords: ["ماء", "شاطئ", "رمل", "سمك", "موج", "سباحة", "سفينة", "صيف", "ملح", "أزرق"] },
  { word: "سيارة", forbiddenWords: ["عجلة", "قيادة", "شارع", "بنزين", "سرعة", "مفتاح", "باب", "لون", "محرك", "فرامل"] },
  { word: "طائرة", forbiddenWords: ["مطار", "سفر", "طيار", "سماء", "جناح", "تذكرة", "رحلة", "جواز", "ركاب", "حقيبة"] },
  { word: "مستشفى", forbiddenWords: ["طبيب", "مريض", "دواء", "عملية", "ممرضة", "أشعة", "سرير", "طوارئ", "إبرة", "علاج"] },
  { word: "تلفزيون", forbiddenWords: ["شاشة", "قناة", "برنامج", "ريموت", "مسلسل", "أخبار", "إعلان", "جهاز", "بث", "مشاهدة"] },
  { word: "مطبخ", forbiddenWords: ["طبخ", "أكل", "موقد", "فرن", "سكين", "طنجرة", "طعام", "وصفة", "توابل", "بوتاجاز"] },
  { word: "جوال", forbiddenWords: ["هاتف", "اتصال", "واتساب", "شاشة", "تطبيق", "شحن", "كاميرا", "إنترنت", "رسالة", "بطارية"] },
  { word: "فيل", forbiddenWords: ["خرطوم", "ضخم", "غابة", "عاج", "رمادي", "حيوان", "أفريقيا", "ثقيل", "نباتي", "قطيع"] },
  { word: "قهوة", forbiddenWords: ["بن", "فنجان", "حار", "مر", "صباح", "كافيه", "خفق", "مقهى", "تركي", "نشاط"] },
  { word: "شجرة", forbiddenWords: ["أوراق", "غابة", "جذع", "ظل", "فاكهة", "تقطيع", "أخضر", "نمو", "جذور", "خشب"] },
  { word: "صحراء", forbiddenWords: ["رمال", "جمل", "حرارة", "واحة", "ظمأ", "رحلة", "سراب", "خيمة", "قبيلة", "ريح"] },
  { word: "برج", forbiddenWords: ["طابق", "مصعد", "بناء", "ارتفاع", "شقة", "مكتب", "معماري", "حديد", "أسمنت", "إيفل"] },
  { word: "موسيقى", forbiddenWords: ["أغنية", "صوت", "آلة", "نغمة", "غناء", "إيقاع", "كمان", "مطرب", "فرقة", "ألحان"] },
  { word: "قطة", forbiddenWords: ["هريرة", "مخالب", "ميو", "فأر", "صوف", "قفز", "شارب", "ذيل", "حيوان", "أليف"] },
  { word: "بيت", forbiddenWords: ["سكن", "باب", "نافذة", "غرفة", "سقف", "عائلة", "شارع", "جيران", "إيجار", "مبنى"] },
  { word: "تفاحة", forbiddenWords: ["فاكهة", "أحمر", "أخضر", "حامض", "شجر", "عصير", "طعم", "حبة", "طازج", "بستان"] },
  { word: "نار", forbiddenWords: ["حرق", "لهب", "دخان", "حريق", "حرارة", "وقود", "إطفاء", "خطر", "أحمر", "ضوء"] },
  { word: "مطر", forbiddenWords: ["سحاب", "ماء", "قطرة", "مظلة", "برق", "رعد", "برودة", "شتاء", "فيضان", "سماء"] },
  { word: "أسد", forbiddenWords: ["غابة", "ملك", "زئير", "شعر", "افتراس", "نمر", "حديقة", "أصفر", "لحم", "شجاع"] },
  { word: "قمر", forbiddenWords: ["ليل", "شمس", "نجوم", "فضاء", "سماء", "هلال", "ضوء", "بدر", "أبيض", "نور"] },
  { word: "كمبيوتر", forbiddenWords: ["لابتوب", "شاشة", "كيبورد", "ماوس", "إنترنت", "برمجة", "ألعاب", "جهاز", "معالج", "تكنولوجيا"] },
  { word: "كتاب", forbiddenWords: ["قراءة", "صفحة", "غلاف", "قصة", "مكتبة", "مؤلف", "رواية", "ورق", "كلمات", "معلومات"] },
  { word: "طبيب", forbiddenWords: ["مريض", "مستشفى", "علاج", "دواء", "أبيض", "عيادة", "سماعة", "ألم", "صحة", "عملية"] },
  { word: "قلم", forbiddenWords: ["حبر", "رصاص", "كتابة", "ورق", "مدرسة", "دفتر", "امتحان", "أزرق", "أحمر", "خط"] },
  { word: "شمس", forbiddenWords: ["نهار", "قمر", "نور", "أشعة", "حرارة", "صيف", "أصفر", "سماء", "غروب", "شروق"] },
  { word: "ساعة", forbiddenWords: ["وقت", "دقائق", "ثواني", "يد", "حائط", "عقارب", "موعد", "رقمية", "منبه", "تأخير"] },
  { word: "عصفور", forbiddenWords: ["طير", "يطير", "شجرة", "سماء", "جناح", "عش", "ريش", "صوصو", "تغريد", "صغير"] },
  { word: "ذهب", forbiddenWords: ["معدن", "غالي", "أصفر", "فضة", "مجوهرات", "خاتم", "سعر", "ثمين", "شراء", "زينة"] },
  { word: "بطيخ", forbiddenWords: ["أحمر", "أخضر", "فاكهة", "بذر", "صيف", "عصير", "حلو", "كبير", "ماء", "أكل"] },
  { word: "خبز", forbiddenWords: ["عجين", "فرن", "مخبز", "طحين", "أكل", "فطور", "رغيف", "حار", "قمح", "أبيض"] },
  { word: "ثلج", forbiddenWords: ["أبيض", "بارد", "شتاء", "ماء", "جبل", "تزلج", "جليد", "مطر", "تجميد", "ذوبان"] },
  { word: "عسل", forbiddenWords: ["نحل", "أصفر", "حلو", "سكر", "شفاء", "زهرة", "طبيعي", "دواء", "لزج", "مفيد"] },
  { word: "عنكبوت", forbiddenWords: ["شبكة", "حشرة", "أرجل", "ثمانية", "زاوية", "خوف", "سام", "سقف", "خيوط", "أسود"] },
  { word: "حذاء", forbiddenWords: ["قدم", "لبس", "مشي", "جلد", "رياضة", "مقاس", "رباط", "شراب", "نعل", "محل"] },
  { word: "نظارة", forbiddenWords: ["عين", "نظر", "شمس", "زجاج", "لبس", "أعمى", "قراءة", "عدسات", "طبيب", "إطار"] },
  { word: "دراجة", forbiddenWords: ["عجلتين", "رياضة", "ركوب", "شارع", "بدال", "توازن", "فرامل", "سرعة", "خوذة", "سيكل"] },
  { word: "قلب", forbiddenWords: ["حب", "دم", "أحمر", "نبض", "شريان", "صدر", "عاطفة", "حياة", "مريض", "رسم"] },
  { word: "سيف", forbiddenWords: ["حرب", "سلاح", "حديد", "درع", "معركة", "فارس", "حاد", "طعن", "قتال", "قديم"] },
  { word: "صابون", forbiddenWords: ["غسيل", "ماء", "نظافة", "رغوة", "حمام", "يد", "عطر", "شامبو", "ليف", "جسم"] },
  { word: "خيمة", forbiddenWords: ["صحراء", "تخييم", "رحلة", "نار", "نوم", "شتاء", "بر", "قماش", "ليل", "بدو"] },
  { word: "سفينة", forbiddenWords: ["بحر", "قارب", "ركاب", "بضائع", "ميناء", "أمواج", "محيط", "غرق", "قبطان", "طاقم"] },
  { word: "حديقة", forbiddenWords: ["شجر", "ورد", "عشب", "أطفال", "لعب", "خضار", "منتزه", "جلوس", "عائلة", "خارج"] },
  { word: "طريق", forbiddenWords: ["شارع", "سفر", "سيارة", "إسفلت", "طويل", "مرور", "يمين", "يسار", "رصيف", "نهاية"] },
  { word: "مفتاح", forbiddenWords: ["باب", "قفل", "حديد", "بيت", "سيارة", "فتح", "إغلاق", "ضيع", "سلسلة", "نسخة"] },
  { word: "رسالة", forbiddenWords: ["بريد", "ورق", "كتابة", "ظرف", "إرسال", "قراءة", "جوال", "واتساب", "بريد إلكتروني", "نص"] },
  { word: "حليب", forbiddenWords: ["بقر", "أبيض", "شرب", "كالسيوم", "صباح", "أطفال", "عظم", "كوب", "قهوة", "مفيد"] },
  { word: "جبل", forbiddenWords: ["ارتفاع", "تسلق", "صخر", "قمة", "وادي", "طبيعة", "حجر", "عالي", "ثلج", "منحدر"] },
  { word: "حلم", forbiddenWords: ["نوم", "ليل", "خيال", "تفسير", "كابوس", "رؤية", "سرير", "عقل", "يصحى", "قصة"] }
];

export const STATIC_PROMPTS = PROMPTS;
export const STATIC_WORDS = WORDS;
